### ISSUE TITLE
UnhandledPromiseRejectionWarning 

### ISSUE THREAD

**Issue by MacFlagg** [hoobs-org/HOOBS#1210] opened 2021-04-05 23:46 UTC
**Description**
I got the following error: UnhandledPromiseRejectionWarning

**Version**

HOOBS  .3.5
Node v14.15.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**

Harmony (HOOBS certified) v1.5.1
Ring (HOOBS certified) v9.15.6
OnStar v1.5.1

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYKTD9",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "REDACTED"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "REDACTED",
        "username": "3A:95:38:E5:2E:11"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "OnStar",
            "plugin_map": {
                "plugin_name": "homebridge-onstar",
                "index": 0
            },
            "name": "Volt",
            "deviceId": "REDACTED",
            "vin": "REDACTED",
            "username": "REDACTED",
            "password": "REDACTED",
            "onStarPin": "REDACTED",
            "enableAlert": false,
            "enableCharger": false,
            "enableDoors": true,
            "doorsDefaultToUnlocked": false
        }
    ],
    "platforms": [
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "refreshToken": "REDACTED“,
            "hideCameraMotionSensor": true,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "showPanicButtons": true,
            "avoidSnapshotBatteryDrain": false,
            "hideDeviceIds": [],
            "locationIds": [],
            "onlyDeviceTypes": []
        },
        {
            "platform": "HarmonyHubWebSocket",
            "plugin_map": {
                "plugin_name": "homebridge-harmony"
            },
            "name": "Harmony",
            "hubIP": "192.168.1.196",
            "hubName": "Theater Room",
            "mainActivity": "Vizio",
            "activitiesToPublishAsInputForTVMode": [],
            "remoteOverrideCommandsList": [],
            "activitiesToPublishAsAccessoriesSwitch": [],
            "skippedIfSameStateActivities": [],
            "devicesToPublishAsAccessoriesSwitch": [],
            "sequencesToPublishAsAccessoriesSwitch": [],
            "homeControlsToPublishAsAccessoriesSwitch": [],
            "otherPlatforms": []
        }
    ]

```

**Post your log**

UnhandledPromiseRejectionWarning: Error: SIP request made after call was destroyed
4/4/2021, 5:51:01 PM at SipCall.request (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:117:35)
4/4/2021, 5:51:01 PM at SipCall.sendKeyFrameRequest (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:188:21)
4/4/2021, 5:51:01 PM at SipCall.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:216:24)
4/4/2021, 5:51:01 PM at Generator.next (<anonymous>)
4/4/2021, 5:51:01 PM at fulfilled (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:5:58)
4/4/2021, 5:51:01 PM (node:1525) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)

**Additional context**

**Version**

HOOBS v3.3.5
Node v14.15.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**

Harmony (HOOBS certified) v1.5.1
Ring (HOOBS certified) v9.15.6
OnStar v1.5.1

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYKTD9",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "REDACTED"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "REDACTED",
        "username": "3A:95:38:E5:2E:11"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "OnStar",
            "plugin_map": {
                "plugin_name": "homebridge-onstar",
                "index": 0
            },
            "name": "Volt",
            "deviceId": "REDACTED",
            "vin": "REDACTED",
            "username": "REDACTED",
            "password": "REDACTED",
            "onStarPin": "REDACTED",
            "enableAlert": false,
            "enableCharger": false,
            "enableDoors": true,
            "doorsDefaultToUnlocked": false
        }
    ],
    "platforms": [
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "homebridge-ring"
            },
            "refreshToken": "REDACTED“,
            "hideCameraMotionSensor": true,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "showPanicButtons": true,
            "avoidSnapshotBatteryDrain": false,
            "hideDeviceIds": [],
            "locationIds": [],
            "onlyDeviceTypes": []
        },
        {
            "platform": "HarmonyHubWebSocket",
            "plugin_map": {
                "plugin_name": "homebridge-harmony"
            },
            "name": "Harmony",
            "hubIP": "192.168.1.196",
            "hubName": "Theater Room",
            "mainActivity": "Vizio",
            "activitiesToPublishAsInputForTVMode": [],
            "remoteOverrideCommandsList": [],
            "activitiesToPublishAsAccessoriesSwitch": [],
            "skippedIfSameStateActivities": [],
            "devicesToPublishAsAccessoriesSwitch": [],
            "sequencesToPublishAsAccessoriesSwitch": [],
            "homeControlsToPublishAsAccessoriesSwitch": [],
            "otherPlatforms": []
        }
    ]

```

**Post your log**

4/5/2021, 2:34:56 PM [Harmony] (Harmony)WARNING - socket closed
4/5/2021, 2:35:16 PM [Harmony] (Harmony)ERROR (1)- refreshCurrentActivity TimeoutError: Can't open WebSocket within allowed timeout: 10000 ms. - Stack : TimeoutError: Can't open WebSocket within allowed timeout: 10000 ms.
    at PromiseController._handleTimeout (/home/hoobs/.hoobs/node_modules/promise-controller/src/index.js:172:19)
    at Timeout.<anonymous> (/home/hoobs/.hoobs/node_modules/promise-controller/src/index.js:178:43)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
4/5/2021, 2:35:41 PM Error: connect EHOSTUNREACH 192.168.1.196:8088
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
4/5/2021, 2:35:41 PM Got SIGTERM, shutting down Bridge...
4/5/2021, 2:35:41 PM [Harmony] INFO - shutdown
4/5/2021, 2:35:41 PM [Harmony] INFO - shutdown

```
I also got this error for the very 1st time today:

UnhandledPromiseRejectionWarning: Error: SIP request made after call was destroyed
4/4/2021, 5:51:01 PM at SipCall.request (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:117:35)
4/4/2021, 5:51:01 PM at SipCall.sendKeyFrameRequest (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:188:21)
4/4/2021, 5:51:01 PM at SipCall.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:216:24)
4/4/2021, 5:51:01 PM at Generator.next (<anonymous>)
4/4/2021, 5:51:01 PM at fulfilled (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/api/sip-call.js:5:58)
4/4/2021, 5:51:01 PM (node:1525) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)

**Additional context**

**Comment by MacFlagg** [comment] 2021-04-06 00:46
New Error Log: Got SIGINT, shutting down Bridge...

4/5/2021, 8:39:00 PM [Harmony] (Harmony)INFO - Loading activities...
4/5/2021, 8:39:00 PM [Harmony] (Harmony)Error - Error retrieving info from hub : network timeout at: http://192.168.1.196:8088/-(2)
4/5/2021, 8:39:10 PM [Harmony] (Harmony)INFO - Loading activities...
4/5/2021, 8:39:10 PM [Harmony] (Harmony)Error - Error retrieving info from hub : network timeout at: http://192.168.1.196:8088/-(3)
4/5/2021, 8:39:14 PM Got SIGINT, shutting down Bridge...
4/5/2021, 8:39:14 PM [Harmony] INFO - shutdown
4/5/2021, 8:39:14 PM [Harmony] INFO - shutdown

**Comment by MacFlagg** [comment] 2021-04-06 23:59
The latest errors on 04/06/2021

[Harmony] (Harmony)WARNING - socket closed
4/6/2021, 7:52:26 PM [Harmony] (Harmony)WARNING - socket closed
4/6/2021, 7:56:45 PM [Harmony-TV A2D1@Active] The read handler for the characteristic 'Active' on the accessory 'Harmony-TV A2D1' was slow to respond!
4/6/2021, 7:56:51 PM [Harmony-TV A2D1@Active] The read handler for the characteristic 'Active' on the accessory 'Harmony-TV A2D1' didn't respond at all!. Please check that you properly call the callback!
4/6/2021, 7:58:11 PM [Harmony] (Harmony)ERROR (1)- refreshCurrentActivity Error: WebSocket closed with reason: undefined (undefined). - Stack : Error: WebSocket closed with reason: undefined (undefined).
    at WebSocketAsPromised._handleClose (/home/hoobs/.hoobs/node_modules/websocket-as-promised/src/index.js:353:19)
    at WebSocket.listener (/home/hoobs/.hoobs/node_modules/websocket-as-promised/src/index.js:311:64)
    at WebSocket.emit (events.js:315:20)
    at WebSocket.emitClose (/home/hoobs/.hoobs/node_modules/harmony-websocket/node_modules/ws/lib/websocket.js:198:10)
    at Socket.socketOnClose (/home/hoobs/.hoobs/node_modules/harmony-websocket/node_modules/ws/lib/websocket.js:886:15)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:673:12)
4/6/2021, 7:58:11 PM [Harmony] (Harmony)WARNING - socket closed

**Comment by MacFlagg** [comment] 2021-04-10 19:52
Latest crash:

4/10/2021, 7:49:59 AM [Ring] Ring connected to socket.io server
4/10/2021, 7:59:06 AM [Harmony] (Harmony)WARNING - socket closed
4/10/2021, 8:16:12 AM [Harmony] (Harmony)WARNING - socket closed
4/10/2021, 8:45:03 AM [Harmony] (Harmony)WARNING - socket closed
4/10/2021, 9:01:16 AM [Harmony] (Harmony)WARNING - socket closed
4/10/2021, 9:58:53 AM [Harmony-TV A2D1@Active Identifier] The read handler for the characteristic 'Active Identifier' on the accessory 'Harmony-TV A2D1' was slow to respond!
4/10/2021, 9:58:59 AM [Harmony-TV A2D1@Active Identifier] The read handler for the characteristic 'Active Identifier' on the accessory 'Harmony-TV A2D1' didn't respond at all!. Please check that you properly call the callback!
4/10/2021, 9:59:31 AM [Harmony] (Harmony)ERROR (1)- refreshCurrentActivity Error: WebSocket closed with reason: undefined (undefined). - Stack : Error: WebSocket closed with reason: undefined (undefined).
    at WebSocketAsPromised._handleClose (/home/hoobs/.hoobs/node_modules/websocket-as-promised/src/index.js:353:19)
    at WebSocket.listener (/home/hoobs/.hoobs/node_modules/websocket-as-promised/src/index.js:311:64)
    at WebSocket.emit (events.js:315:20)
    at WebSocket.emitClose (/home/hoobs/.hoobs/node_modules/harmony-websocket/node_modules/ws/lib/websocket.js:198:10)
    at Socket.socketOnClose (/home/hoobs/.hoobs/node_modules/harmony-websocket/node_modules/ws/lib/websocket.js:886:15)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:673:12)
4/10/2021, 9:59:31 AM [Harmony] (Harmony)WARNING - socket closed
4/10/2021, 10:06:27 AM [Harmony] (Harmony)WARNING - socket closed
4/10/2021, 11:49:59 AM [Ring] Reconnecting location socket.io connection
4/10/2021, 11:50:00 AM [Ring] Creating location socket.io connection - Brunswick
4/10/2021, 11:50:01 AM [Ring] Ring connected to socket.io server
4/10/2021, 3:04:35 PM [Harmony] (Harmony)WARNING - socket closed
4/10/2021, 3:04:55 PM [Harmony] (Harmony)ERROR (1)- refreshCurrentActivity TimeoutError: Can't open WebSocket within allowed timeout: 10000 ms. - Stack : TimeoutError: Can't open WebSocket within allowed timeout: 10000 ms.
    at PromiseController._handleTimeout (/home/hoobs/.hoobs/node_modules/promise-controller/src/index.js:172:19)
    at Timeout.<anonymous> (/home/hoobs/.hoobs/node_modules/promise-controller/src/index.js:178:43)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
4/10/2021, 3:05:21 PM Error: connect EHOSTUNREACH 192.168.1.196:8088
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
4/10/2021, 3:05:21 PM Got SIGTERM, shutting down Bridge...
4/10/2021, 3:05:21 PM [Harmony] INFO - shutdown
4/10/2021, 3:05:21 PM [Harmony] INFO - shutdown

**Comment by bwp91** [comment] 2021-04-19 08:06
Try uninstalling and reinstalling the harmony plugin. I think this is what is causing the bridge to crash.

`Error: SIP request made after call was destroyed`

This can often appear when for example starting a live view of the ring camera when the bridge is shutting down. I've seen it a couple of times but I don't think it's your main issue.

I think the issue is with the harmony plugin. As I said, try uninstalling and reinstalling. Although it's not a new version of the harmony plugin, the reinstall should update one of the dependencies which has fixed a bug related to closing sockets.

**Comment by MacFlagg** [comment] 2021-04-19 11:34
Bwp91, I have tried uninstalling and reinstalling the Harmony plug-in multiple times. I’ve factory reset my HOOBS hub several times. To configure the Harmony plug-in, I only fill in the 4 fields that the plug-in needs to work: Name of Hub, IP address, Name of Hub in app, and main activity. None of this fixes the issue.

**Comment by bwp91** [comment] 2021-04-19 11:39
>  Although it's not a new version of the harmony plugin, the reinstall should update one of the dependencies which has fixed a bug related to closing sockets.

I'm talking about an update that was released within the last couple of days.

**Comment by MacFlagg** [comment] 2021-04-19 18:00
Ok. I have uninstalled and re-installed the plug-in. Let’s see how it goes.

**Closed** 2021-06-11 01:56 UTC
Labels: bug, discovery, wontfix
