### ISSUE TITLE
Problem after Harmony Plugin Update

### ISSUE THREAD

**Issue by TheBassfly** [hoobs-org/HOOBS#428] opened 2020-01-16 15:52 UTC
Hey

I recently updated the Harmony Plugin and now Hoobs is crashing sostatntly with a few error messages regarding the connection to the hub.

Right now I even can't access the pi via SSH.

Any Solutions?

**Comment by mkellsy** [comment] 2020-01-16 17:40
SSH is part of the operating system, of that is not working you have bigger problems.

**Comment by TheBassfly** [comment] 2020-01-16 21:23
It looks like.
Hoobs takes around 20 minutes to boot. Then I can reach the gui but homebridge service is not running.
When I leave it running a few hours later it's off again. The only I changed the last days was the update of the harmony plug-in.

**Comment by mkellsy** [comment] 2020-01-16 23:56
Can you post the logs once you get into the UI.

**Comment by TheBassfly** [comment] 2020-01-21 07:37
So, it was running the last days but last night I got a homebridge crash again.
Here is part of the log:

[Homebridge] [1/21/2020, 04:14:22] [HarmonyHub] ERROR - refreshCurrentActivity Error: WebSocket closed with reason: connection failed (1006).
[Homebridge] [1/21/2020, 04:14:22] [HarmonyHub] ERROR - refreshCurrentActivity Error: WebSocket closed with reason: connection failed (1006).
[Homebridge] [1/21/2020, 04:14:22] [HarmonyHub] ERROR - refreshCurrentActivity Error: WebSocket closed with reason: connection failed (1006).
[Homebridge] <--- Last few GCs --->
[Homebridge] [24471:0x26ba700] 72253567 ms: Mark-sweep 226.8 (231.6) -> 226.7 (231.8) MB, 4182.7 / 2.0 ms  (average mu = 0.104, current mu = 0.002) allocation failure scavenge might not succeed
[Homebridge] [24471:0x26ba700] 72257298 ms: Mark-sweep 227.0 (231.8) -> 226.9 (232.1) MB, 3722.5 / 2.8 ms  (average mu = 0.057, current mu = 0.002) allocation failure scavenge might not succeed
[Homebridge] <--- JS stacktrace --->
[Homebridge] ==== JS stack trace =========================================
[Homebridge] 0: ExitFrame [pc: 0xe52060]
[Homebridge] Security context: 0x494fe935 <JSObject>
[Homebridge] 1: getCurrentActivity [0x5851bbb5] [/home/hoobs/.hoobs/node_modules/harmony-websocket/lib/harmony-websocket.js:~225] [pc=0x4dc3bf10](this=0x73d65555 <EventEmitter map = 0x44874f91>)
[Homebridge] 2: /* anonymous */ [0x43dbf675] [/home/hoobs/.hoobs/node_modules/homebridge-harmony/harmonyBase.js:~290] [pc=0x2ee3da30](this=0x452c22f5 <JSGlobal Object>,0x703055e1 <E map = 0x3f9...
[Homebridge] FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
[Homebridge] Writing Node.js report to file: report.20200121.041516.24471.0.001.json
[Homebridge] Node.js report completed
[Homebridge] <--- Last few GCs --->
[Homebridge] [465:0x21fd700] 355061260 ms: Mark-sweep 227.6 (232.3) -> 227.4 (232.3) MB, 2850.0 / 2.1 ms  (average mu = 0.098, current mu = 0.003) allocation failure scavenge might not succeed
[Homebridge] [465:0x21fd700] 355065154 ms: Mark-sweep 227.7 (232.3) -> 227.6 (232.5) MB, 3885.0 / 1.5 ms  (average mu = 0.048, current mu = 0.002) allocation failure scavenge might not succeed
[Homebridge] <--- JS stacktrace --->
[Homebridge] ==== JS stack trace =========================================
[Homebridge] 0: ExitFrame [pc: 0xdc5d3c]
[Homebridge] Security context: 0x2fcce225 <JSObject>
[Homebridge] 1: _send [0x2b241389] [internal/child_process.js:~687] [pc=0x23c5d948](this=0x27a01205 <process map = 0x28988af9>,0x451adee9 <Object map = 0x289a4d49>,0x39080275 <undefined>,0x451adf1d <Object map = 0x289a4d71>,0x39080275 <undefined>)
[Homebridge] 2: log [0x32fcce35] [/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/logger.js:~45] [pc=0x23c4b674](this=0x4eef5e5d <Logg...
[Homebridge] FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory



Looks like that the harmony plug-in starts to get a. Inch of errors until the homebridge crashes then.

**Comment by TheBassfly** [comment] 2020-01-22 17:48
So the last days, the Homebridge always stopped working on random times a day. o my luck the hoops ui was always available so I could se in the log always a problem with the Harmony Plugin wich caused some errors and then the crash. I just hit "start service" and everything worked fine again until the next group of errors from the harmony.

**Comment by TheBassfly** [comment] 2020-01-24 08:49
Okay, meanwhile I also made an issue at the Homebridge-Harmony hub and the developer there looked with me. I seems, that the Problem is mainly caused by hoobs.

**Comment by mkellsy** [comment] 2020-01-24 15:56
HOOBS installs plugins in ~/.hoobs/node_modules. This shouldn't be different then installing it in the global scope.

Whats happening is the websocket is failing to connect, and retrying. The failures are leaking memory.

I noticed that harmony-websocket creates a socket on port 8088. By chance are you running a system with firewalld?

**Comment by mkellsy** [comment] 2020-01-24 16:00
I reviewed the lines of code that are causing this. issue.

In https://github.com/nicoduj/homebridge-harmony/blob/Dynamic-Platform/harmonyBase.js around line 284.
```javascript
this.harmony
    .getCurrentActivity()
    .then(response => {
        harmonyPlatform.refreshCurrentActivity(response);
            if (!callbackDone) callback();
        })
    .catch(e => {
        harmonyPlatform.log('ERROR - refreshCurrentActivity ' + e);
        harmonyPlatform.refreshCurrentActivity(
            HarmonyConst.CURRENT_ACTIVITY_NOT_SET_VALUE
        );
        if (!callbackDone) callback();
    });
```

Doing something like this, putting a half second gap between retries could make this more memory friendly.
```javascript
this.harmony
    .getCurrentActivity()
    .then(response => {
        harmonyPlatform.refreshCurrentActivity(response);
            if (!callbackDone) callback();
        })
    .catch(e => {
        harmonyPlatform.log('ERROR - refreshCurrentActivity ' + e);
        setTimeout(() => {
            harmonyPlatform.refreshCurrentActivity(
                HarmonyConst.CURRENT_ACTIVITY_NOT_SET_VALUE
            );
            if (!callbackDone) callback();
        }, 500);
    });
```

I don't know if this will help, but I am disconnecting my Harmony Hub from SmartThings to test this with HOOBS.

**Comment by nicoduj** [comment] 2020-01-24 16:15
Hi, it is not doing a retry, harmonyPlform is not harmonyBase. It is only setting the activity to unset value . that is what is strange to me, since when I generate an error manually in this code, like this : 

```javascript

      this.harmony
        .getCurrentActivity()
        .then(response => {
//TEST
          harmonyPlatform.log('ERROR - refreshCurrentActivity TEST');
          harmonyPlatform.refreshCurrentActivity(
            HarmonyConst.CURRENT_ACTIVITY_NOT_SET_VALUE
          );
          if (!callbackDone) callback();
/*
          harmonyPlatform.refreshCurrentActivity(response);
          if (!callbackDone) callback();
*/

        })
        .catch(e => {
          harmonyPlatform.log('ERROR - refreshCurrentActivity ' + e);
          harmonyPlatform.refreshCurrentActivity(
            HarmonyConst.CURRENT_ACTIVITY_NOT_SET_VALUE
          );
          if (!callbackDone) callback();
        });

```

I only get the error once,  no retry : 

```batch

[24/01/2020 à 10:01:30] [NicoHarmonyHub] ERROR - refreshCurrentActivity TEST
[24/01/2020 à 10:01:30] [NicoHarmonyHub] keysMap is :{}

```

might be missing something .

**Comment by mkellsy** [comment] 2020-01-24 16:22
True. I'm at work and don't have access to this yet. There are many things for me to look at.
1. This plugins use of websockets, since HOOBS uses websockets too there might be a conflict.
2. In the next version of HOOBS we are separating the plugins from HOOBS modules, there might be some conflicts there too.

I truly think this is not an issue with either this plugin or HOOBS, but how NPM shares modules.

**Comment by nicoduj** [comment] 2020-01-24 16:26
Yes, I agree, Especially since the websocket as promised module  is referenced at different levels there maybe with some differents versions.

Moreover, @TheBassfly problem started in my last version, and I have updated dependency from 0.10.1 to 1.10.1 on websocket-as-promised. 

Since I am dependant of harmony-websocket, which used latest version in its package.json, I am beginning to think that It might be safer not to reference websocket at all directly (I don't think I am using it in latest version but have to check)

**Comment by TheBassfly** [comment] 2020-01-25 07:38
Thank you guys for your support.

There is a new version out and I give it a try in the moment.

**Comment by TheBassfly** [comment] 2020-01-26 16:36
So the Version 1.2. from yesterday didn't helped.

Today I got a Crash again:

[Homebridge] [1/26/2020, 17:15:26] [HarmonyHub] ERROR - refreshCurrentActivity TimeoutError: Can't open WebSocket within allowed timeout: 10000 ms.
[Homebridge] [1/26/2020, 17:15:26] [HarmonyHub] ERROR - refreshCurrentActivity TimeoutError: Can't open WebSocket within allowed timeout: 10000 ms.
[Homebridge] [1/26/2020, 17:15:26] [HarmonyHub] ERROR - refreshCurrentActivity TimeoutError: Can't open WebSocket within allowed timeout: 10000 ms.
[Homebridge] [1/26/2020, 17:15:26] [HarmonyHub] ERROR - refreshCurrentActivity TimeoutError: Can't open WebSocket within allowed timeout: 10000 ms.
[Homebridge] [1/26/2020, 17:15:26] [HarmonyHub] ERROR - refreshCurrentActivity TimeoutError: Can't open WebSocket within allowed timeout: 10000 ms.
[Homebridge] [1/26/2020, 17:15:26] [HarmonyHub] ERROR - refreshCurrentActivity TimeoutError: Can't open WebSocket within allowed timeout: 10000 ms.
[Homebridge] [1/26/2020, 17:15:26] [HarmonyHub] ERROR - refreshCurrentActivity TimeoutError: Can't open WebSocket within allowed timeout: 10000 ms.
[Homebridge] <--- Last few GCs --->
[Homebridge] [464:0x21e0700] 35765654 ms: Mark-sweep 227.8 (234.8) -> 227.2 (235.3) MB, 2945.7 / 0.1 ms  (average mu = 0.127, current mu = 0.070) allocation failure scavenge might not succeed
[Homebridge] [464:0x21e0700] 35769596 ms: Mark-sweep 228.6 (235.3) -> 228.0 (235.8) MB, 3908.2 / 0.1 ms  (average mu = 0.065, current mu = 0.008) allocation failure scavenge might not succeed
[Homebridge] <--- JS stacktrace --->
[Homebridge] ==== JS stack trace =========================================
[Homebridge] Security context: 0x2368e225 <JSObject>
[Homebridge] 0: builtin exit frame: stringify(this=0x5fa26611 <Object map = 0x24002249>,0x4af80275 <undefined>,0x4af80275 <undefined>,0x70267b25 <Object map = 0x4de64bb9>,0x5fa26611 <Object map = 0x24002249>)
[Homebridge] 1: arguments adaptor frame: 1->3
[Homebridge] 2: _send [0x388bdb59] [internal/child_process.js:~687] [pc=0x31bef748](this=0x5fa01205 <process map = 0x4de48aa9>,0x70267b25 <Object map = 0x4de64bb9>,0x4af8027...
[Homebridge] FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

**Comment by nicoduj** [comment] 2020-02-16 08:45
@mkellsy Did you have any chance to test the plugin with hoobs, regarding this issue ? I have reports of other users with such problems, but it seems to happen mainly in hoobs. I am trying to understand it, but right now can't reproduce.

**Comment by BobbySlope** [comment] 2020-03-21 08:17
looks like the issue is solved from plugin dev side
https://github.com/nicoduj/homebridge-harmony/issues/217
closing, reopen if issue still exists

**Closed by BobbySlope** 2020-03-21 08:17 UTC
Labels: discovery, plugins, tracked
