### ISSUE TITLE
New Hoobs in a box

### ISSUE THREAD

**Issue by bfmwest** [hoobs-org/HOOBS#1477] opened 2021-08-23 14:08 UTC
**Description**

**Version**
Please include the version of HOOBS you are using.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment] 2021-08-23 15:26
Closing. No description on what the problem is.
“A clear and concise description of what the bug is.“

**Comment by bfmwest** [comment] 2021-08-23 15:47
I received the Hoobs in a Box last week, during setup it said updates available. After the update was complete the Hoobs now will not connect
to Hoobs.local or allow me to login. I’ve tried to use the IP address that the router has assigned  but, it comes back with invalid IP address.


Regards,
Bruce Field
***@***.***

**Comment by EddieDSuza** [comment] 2021-08-23 16:13
If you're using a mesh network, you will have to connect the HOOBS Box into the main node for it to be accessible across the network.

**Comment by mkellsy** [comment] 2021-08-23 17:47
Is the red led list on the device?

**Comment by bfmwest** [comment] 2021-08-23 19:13
Yes, I can see a red LED in the box.
I do not have a nest network.

Regards,
Bruce Field
***@***.***

**Comment by mkellsy** [comment] 2021-08-23 19:39
Can you access the terminal at http://hoobs.local:9090?

**Comment by bfmwest** [comment] 2021-08-23 19:46
Yes


Regards,
Bruce Field
***@***.***

**Comment by mkellsy** [comment] 2021-08-23 19:49
OK. The username is **hoobs** and the password is **hoobsadmin**.

Then run this command.
```
sudo systemctl status hoobsd
```

Also can you post your logs?
```
sudo hbs log -d
```

**Comment by bfmwest** [comment] 2021-08-23 19:52
This is what I get.


● hoobsd.service - HOOBSD
   Loaded: loaded (/etc/systemd/system/hoobsd.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-08-23 13:50:47 MDT; 3s ago
 Main PID: 22756 (hoobsd)
    Tasks: 7 (limit: 2059)
   CGroup: /system.slice/hoobsd.service
           └─22756 hoobsd




Regards,
Bruce Field
***@***.***

**Comment by mkellsy** [comment] 2021-08-23 19:53
What do you get when you run?
```
sudo hbs log -d
```

**Comment by bfmwest** [comment] 2021-08-23 19:55
Nothing at all



Regards,
Bruce Field
***@***.***

**Comment by mkellsy** [comment] 2021-08-23 19:59
What about this
```
node -v
```

**Comment by bfmwest** [comment] 2021-08-23 20:00
v14.17.5



Regards,
Bruce Field
***@***.***

**Comment by mkellsy** [comment] 2021-08-23 20:02
OK. Run this.
```
ip address
```

**Comment by bfmwest** [comment] 2021-08-23 20:03
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:30:08:ce brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.36/24 brd 192.168.1.255 scope global dynamic noprefixroute eth0
       valid_lft 65571sec preferred_lft 65571sec
3: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether 26:dc:5a:1c:bb:31 brd ff:ff:ff:ff:ff:ff




Regards,
Bruce Field
***@***.***

**Comment by mkellsy** [comment] 2021-08-23 20:04
OK. One more command.
```
sudo hbs bridges ls
```

**Comment by bfmwest** [comment] 2021-08-23 20:05
error: unknown command 'bridges'. See 'hbs --help’.



Regards,
Bruce Field
***@***.***

**Comment by mkellsy** [comment] 2021-08-23 20:08
OOPS
```
sudo hbs bridge ls
```

**Comment by bfmwest** [comment] 2021-08-23 20:09
id  | type | display | port | pin        | username          | advertiser
-------------------------------------------------------------------------
hub | hub  | Hub     | 80   | 031-45-154 | 08:3A:F0:99:32:23 |  





Regards,
Bruce Field
***@***.***

**Comment by mkellsy** [comment] 2021-08-23 20:11
This is wired. Everything shows it should work.

http://hoobs.local
or
http://hoobs
or
http://192.168.1.36

**Comment by bfmwest** [comment] 2021-08-23 20:25
Using the IP address returns Safari can’t connect to server.
http://hoobs.local <http://hoobs.local/> comes up but never connects.
Using the Hoobs desktop App for macOS returns No devices and advanced entering IP address returns Invalid IP address.




Regards,
Bruce Field
***@***.***

**Comment by mkellsy** [comment] 2021-08-23 20:31
This might be your Mac. Try using your phone. See if it connects.

**Comment by bfmwest** [comment] 2021-08-23 20:40
nothing works, I tried my iPhone, iPad and Mac none of them will connect

Regards,
Bruce Field
***@***.***

**Comment by mkellsy** [comment] 2021-08-23 20:51
This is wired. Please send an email with your order number to info@hoobs.com. We can troubleshoot and replace components if needed.

**Comment by caspianguirey** [comment] 2021-08-24 18:48
ok

**Comment by caspianguirey** [comment] 2021-08-24 18:49
just sent

**Comment by caspianguirey** [comment] 2021-08-24 18:49
Order #27514] (August 20, 2021)

**Comment by caspianguirey** [comment] 2021-08-24 18:52
have you received it

**Comment by caspianguirey** [comment] 2021-08-24 18:55
yes i received it this morning

**Comment by caspianguirey** [comment] 2021-08-24 18:55
I am in Ireland and I received it at about 10 o’clock this morning I followed the directions and got it briefly to show on my Mac

**Comment by caspianguirey** [comment] 2021-08-24 18:56
I somehow got onto the dashboard it was not through the Mac app then I tried to add some ring cameras but it could not find any devices so on the website which showed my device I tried the update that it said

**Comment by caspianguirey** [comment] 2021-08-24 18:57
![Uploading image.jpg…]()

**Comment by caspianguirey** [comment] 2021-08-24 18:58
![image](https://user-images.githubusercontent.com/89479884/130674124-86f3c729-ecd2-47cd-9982-690f948c7da8.jpg)

**Comment by caspianguirey** [comment] 2021-08-24 18:58
The amber light is flashing I don’t know if that is what it is supposed to do

**Closed** 2021-08-24 18:58 UTC
Labels: bug, discovery

**Comment by askovi** [comment] 2021-08-24 19:00
Caspian,
Please send a direct email to info@hoobs.com for direct assistance. Someone will reach out to you to assist you remotely to configure your device.
