### ISSUE TITLE
Bug on shelly Plugin

### ISSUE THREAD

**Issue by uxen-al** [hoobs-org/HOOBS#692] opened 2020-06-18 07:59 UTC
**Description**
It's impossible to turn off light with a Shelly 2.5 (Turn on is ok)

**Version**

3.2.6
--

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Shelly 
Ring
Chamberlain

**Post your config**

{
    "server": {
        "port": 8080,
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYNL74",
        "polling_seconds": 5,
        "origin": "*"
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-dark",
        "locale": "fr",
        "temp_units": "celsius",
        "country_code": "FR",
        "postal_code": "XXXXX",
        "latitude": "XXXX",
        "longitude": "XXXXX"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "xxxxx",
        "username": "XXXXX"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "Chamberlain",
            "plugin_map": {
                "plugin_name": "homebridge-chamberlain",
                "index": 0
            },
            "name": "Porte de Garage",
            "username": "XXXXXX",
            "password": "XXXXXX",
            "deviceId": "XXXXX"
        },
        {
            "accessory": "Chamberlain",
            "plugin_map": {
                "plugin_name": "homebridge-chamberlain",
                "index": 0
            },
            "name": "Portail",
            "password": "XXXXX",
            "username": "XXXXX",
            "deviceId": "XXXX"
        }
    ],
    "platforms": [
        {
            "platform": "Ring",
            "plugin_map": {
                "plugin_name": "ring"
            },
            "email": "XXXXXX",
            "password": "XXXXXX",
            "refreshToken": "XXXXXXX"
        },
        {
            "platform": "Shelly",
            "name": "Shelly",
            "admin": {
                "enabled": "true",
                "port": 8181
            },
            "username": "XXXXXX",
            "password": "XXXXXXX",
            "plugin_map": {
                "plugin_name": "homebridge-shelly"
            }
        }
    ]
**Post your log**
No log

**Additional context**

In shelly home appli it's ok for turning off. In hoos and in HomeKit it's doesn't work any more.

**Comment by BobbySlope** [comment] 2020-06-18 08:04
the plugin dev is already aware of since you opened the issue there, we can't do anything on our side. duplicate of: https://github.com/alexryd/homebridge-shelly/issues/128

**Closed by BobbySlope** 2020-06-18 08:04 UTC
Labels: bug, discovery
