### ISSUE TITLE
Bridge service not running

### ISSUE THREAD

**Issue by GOTDNRV** [hoobs-org/HOOBS#1103] opened 2021-02-24 01:42 UTC
I have reset the bridge, reset the name, reset the wifi, and reinstalled all devices.  However, I have had this same response now for the past 7 days.  Homebridge 3.3.2.  all plugins with the most recent updates. 
 
Keep getting the following message.
HOOBS listening on port 80.
2/23/2021, 8:30:47 PM Loaded plugin 'homebridge-ring'
2/23/2021, 8:30:47 PM [2/23/2021, 6:30:47 PM] Registering platform 'homebridge-ring.Ring'
2/23/2021, 8:30:48 PM Loaded plugin 'homebridge-simplisafe3'
2/23/2021, 8:30:48 PM Loading 2 platforms...
2/23/2021, 8:30:48 PM [2/23/2021, 6:30:48 PM] Registering platform 'homebridge-simplisafe3.SimpliSafe 3'
2/23/2021, 8:30:48 PM [Ring] Initializing Ring platform...
2/23/2021, 8:30:48 PM [Home Alarm] Initializing homebridge-simplisafe3.SimpliSafe 3 platform...
2/23/2021, 8:30:48 PM TypeError: Cannot read property 'username' of undefined
    at new SS3Platform (/home/hoobs/.hoobs/node_modules/homebridge-simplisafe3/index.js:74:58)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:346:30
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:320:31)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:35)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by askovi** [comment] 2021-03-01 04:02
Duplicate of https://github.com/hoobs-org/HOOBS/issues/1108

**Closed by askovi** 2021-03-01 04:02 UTC
