### ISSUE TITLE
Node Update Breaks HOOBS Box

### ISSUE THREAD

**Issue by wesbro** [hoobs-org/HOOBS#429] opened 2020-01-16 18:59 UTC
I ran the node update and now have a non-working HOOBS box. This is the command I ran:

wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts

I'm now getting [this](https://a.cl.ly/L1ukvQr1) when I go to hoobs.local.

Before I ran the update I was running Homebridge 0.4.50 and Node 10.17.0

**Comment by mkellsy** [comment] 2020-01-16 19:14
Duplicate of #415

**Closed** 2020-02-10 16:33 UTC
Labels: bug, tracked
