### ISSUE TITLE
Safari Not Loading Material Icons

### ISSUE THREAD

**Issue by bgiuriceo** [hoobs-org/HOOBS#162] opened 2019-09-25 11:43 UTC
The menu bar stying is incorrect:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/50047233/65597839-02518300-df68-11e9-860d-07cc933a9e7f.png">

Also, the weather forcast is shown in Chrome but not Safari. (The CSS is broken on both).

**Comment by mkellsy** [comment] 2019-09-25 15:16
The icons on the left are due to Google's material icons.  You need to clear the files in your browser cache. (Not the cookies or history, just the cached images and files)

The weather is an issue I have been trying to track down. This is the first report that it is not showing in Safari. Thank You.

**Comment by mkellsy** [comment] 2019-09-25 15:45
This is an issue on how Safari handles dates all browsers accept this as a date 2019-09-25 12:00:00. Safari doesn't. Safari requires this 2019-09-25T12:00:00.

This is fixed in 3.0.0-beta.56

**Comment by rpolenthon** [comment] 2019-09-25 17:03
@mkellsy 

I get the same behavior as @bgiuriceo every time I type in hoobs.local/SOMETHING

Closing the tab and open it again is the only thing needed.

Maybe you can fix it with this instruction.

**Comment by bgiuriceo** [comment] 2019-09-25 17:08
Closing the tab on either browser does not fix it for me.
b

**Comment by rpolenthon** [comment] 2019-09-25 17:16
@bgiuriceo Then it is another issue in your case

**Comment by mkellsy** [comment] 2019-09-25 18:26
I am not seeing this behavior in Safari. Can you post the browser console? Right Click + Inspect. The console will tell me if Safari can't load the css files and point me in the right direction.

Also in the inspect panel there is a Network tab. It should show a list of files.
Is there a file called app-*.css?
Are there files called chunk-*.css?
Is there a file called material.*.woff? (Important)

The material.woff file is material icons. This is what you are seeing. If this isn't loading it could be the problem. However I need the logs to confirm, since my computer isn't producing the problem. (need to reproduce to test a fix).

Also what version of Safari are you running. Menu -> Safari -> About Safari.

What version of macOS are you running Menu -> Apple -> About this Mac.

**Comment by bgiuriceo** [comment] 2019-09-25 19:49
I replied via email, let me know if you didnt get it.

**Comment by bgiuriceo** [comment] 2019-09-25 19:56
There was a new Sarfari version released this morning:
Version 13.0.1 (14608.2.11.1.11)
Mac OS Mojave 10.4.6


<img width="341" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/50047233/65634703-d3a9cb80-dfac-11e9-8378-2f43601483c8.png">

**Comment by mkellsy** [comment] 2019-09-25 21:23
I re-downloaded the material fonts and added other type incase Safari is looking for a ttf or eot instead of a web font.

Fixed in 3.0.0-beta.57

**Closed by mkellsy** 2019-09-25 21:23 UTC
Labels: 3.0.0, discovery

**Comment by mkellsy** [comment] 2019-09-26 16:27
bgiuriceo is still having issues with this in Safari.
