### ISSUE TITLE
Vivint Plug In - Error1020

### ISSUE THREAD

**Issue by ajtrocks** [hoobs-org/HOOBS#1626] opened 2021-10-28 03:36 UTC
**Description**
I've downloaded the Vivint Plug in, the latest version, 1.6.0, authored by Alexandr Balan. The boxes to enter my email and password were present, however nothing happened when I hit submit. I was able to link my account by manually adding info in configuration, however when I try to get a refresh token, I end up with a cloudfare Error. I used terminal to run vivint_mfa_cli_debug and I always get back Error 1020. Is there a work around that I can have the terminal successfully enter "https://www.vivintsky.com/api/login" or can I change the code somehow to go to a different login web address? 

**Please report the issue to the plugin developer**
We like to help the community, however some issues are out of our control. Please report this to the plugin developer and include a link here.

I am using version 4.0.71.

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
macOS Catalina.

**Post your config**

    "accessories": [],
    "platforms": [
        {
            "platform": "Vivint",
            "refreshToken": "your-vivint-refresh-token",
            "apiLoginRefreshSecs": 1200,
            "password": "my pasword",
            "username": "my email"
        }
    ]
}

```

10/27/2021, 8:45:21 PMVivint BridgeConfiguration change
10/27/2021, 8:45:21 PMvivintbridge stopping
10/27/2021, 8:45:25 PMVivint Bridge starting
10/27/2021, 8:45:29 PMVivint BridgeLoaded plugin '@balansse/homebridge-vivint'
10/27/2021, 8:45:29 PMVivint BridgeLoading 1 platforms...
10/27/2021, 8:45:29 PMVivint BridgeBridge is running on port 52826.
10/27/2021, 8:46:32 PMVivint BridgeConfiguration change
10/27/2021, 8:46:32 PMvivintbridge stopping
10/27/2021, 8:46:36 PMVivint Bridge starting
10/27/2021, 8:46:40 PMVivint BridgeLoaded plugin '@balansse/homebridge-vivint'
10/27/2021, 8:46:40 PMVivint BridgeLoading 1 platforms...
10/27/2021, 8:46:40 PMVivint BridgeBridge is running on port 52826.
10/27/2021, 9:00:12 PMVivint BridgeConfiguration change
10/27/2021, 9:00:12 PMvivintbridge stopping
10/27/2021, 9:00:16 PMVivint Bridge starting
10/27/2021, 9:00:20 PMVivint BridgeLoaded plugin '@balansse/homebridge-vivint'
10/27/2021, 9:00:20 PMVivint BridgeLoading 1 platforms...
10/27/2021, 9:00:20 PMVivint BridgeBridge is running on port 52826.
10/27/2021, 9:07:12 PMHue BridgeWARNINGunhandled rejection: SyntaxError: Unexpected token u in JSON at position 0
10/27/2021, 9:07:14 PMvivintbridge stopping
10/27/2021, 10:30:47 PMHue BridgeWARNINGunhandled rejection: SyntaxError: Unexpected token u in JSON at position 0
10/27/2021, 10:30:47 PMArlo Bridge starting
10/27/2021, 10:30:54 PMArlo BridgeWARNINGNo plugins installed.
10/27/2021, 10:30:54 PMArlo BridgeBridge is running on port 52826.
10/27/2021, 10:31:04 PMArlo BridgeConfiguration change
10/27/2021, 10:31:04 PMarlobridge stopping
10/27/2021, 10:31:08 PMArlo Bridge starting
10/27/2021, 10:31:11 PMArlo BridgeLoaded plugin 'homebridge-arlo'
10/27/2021, 10:31:11 PMArlo BridgeLoading 1 platforms...
10/27/2021, 10:31:11 PMArlo BridgeBridge is running on port 52826.
10/27/2021, 10:31:52 PMArlo BridgeConfiguration change
10/27/2021, 10:31:52 PMarlobridge stopping
10/27/2021, 10:31:56 PMArlo Bridge starting
10/27/2021, 10:31:59 PMArlo BridgeLoaded plugin 'homebridge-arlo'
10/27/2021, 10:31:59 PMArlo BridgeLoading 1 platforms...
10/27/2021, 10:31:59 PMArlo BridgeBridge is running on port 52826.
10/27/2021, 10:39:42 PMHue BridgeWARNINGunhandled rejection: SyntaxError: Unexpected token u in JSON at position 0
10/27/2021, 10:39:42 PMVivint Bridge starting
10/27/2021, 10:39:50 PMVivint BridgeWARNINGNo plugins installed.
10/27/2021, 10:39:50 PMVivint BridgeBridge is running on port 53826.
10/27/2021, 10:40:09 PMVivint BridgeConfiguration change
10/27/2021, 10:40:09 PMvivintbridge stopping
10/27/2021, 10:40:14 PMVivint Bridge starting
10/27/2021, 10:40:17 PMVivint BridgeLoaded plugin '@balansse/homebridge-vivint'
10/27/2021, 10:40:17 PMVivint BridgeLoading 1 platforms...
10/27/2021, 10:40:17 PMVivint BridgeBridge is running on port 53826.
10/27/2021, 10:42:00 PMVivint BridgeConfiguration change
10/27/2021, 10:42:00 PMvivintbridge stopping
10/27/2021, 10:42:04 PMVivint Bridge starting
10/27/2021, 10:42:08 PMVivint BridgeLoaded plugin '@balansse/homebridge-vivint'
10/27/2021, 10:42:08 PMVivint BridgeLoading 1 platforms...
10/27/2021, 10:42:08 PMVivint BridgeBridge is running on port 53826.
10/27/2021, 10:46:06 PMVivint BridgeConfiguration change
10/27/2021, 10:46:06 PMvivintbridge stopping
10/27/2021, 10:46:10 PMVivint Bridge starting
10/27/2021, 10:46:14 PMVivint BridgeLoaded plugin '@balansse/homebridge-vivint'
10/27/2021, 10:46:14 PMVivint BridgeLoading 1 platforms...
10/27/2021, 10:46:14 PMVivint BridgeBridge is running on port 53826.
10/27/2021, 10:51:25 PMVivint BridgeConfiguration change
10/27/2021, 10:51:25 PMvivintbridge stopping
10/27/2021, 10:51:30 PMVivint Bridge starting
10/27/2021, 10:51:33 PMVivint BridgeLoaded plugin '@balansse/homebridge-vivint'
10/27/2021, 10:51:33 PMVivint BridgeLoading 1 platforms...
10/27/2021, 10:51:33 PMVivint BridgeBridge is running on port 53826.
10/27/2021, 10:52:22 PMVivint BridgeConfiguration change
10/27/2021, 10:52:22 PMvivintbridge stopping
10/27/2021, 10:52:26 PMVivint Bridge starting
10/27/2021, 10:52:30 PMVivint BridgeLoaded plugin '@balansse/homebridge-vivint'
10/27/2021, 10:52:30 PMVivint BridgeLoading 1 platforms...
10/27/2021, 10:52:30 PMVivint BridgeBridge is running on port 53826.
10/27/2021, 10:52:36 PMvivintbridge stopping
10/27/2021, 10:52:41 PMVivint Bridge starting
10/27/2021, 10:52:44 PMVivint BridgeLoaded plugin '@balansse/homebridge-vivint'
10/27/2021, 10:52:44 PMVivint BridgeLoading 1 platforms...
10/27/2021, 10:52:44 PMVivint BridgeBridge is running on port 53826.
10/27/2021, 10:57:31 PMVivint BridgeConfiguration change
10/27/2021, 10:57:31 PMvivintbridge stopping
10/27/2021, 10:57:33 PMvivintbridge stopping
10/27/2021, 10:57:36 PMVivint Bridge starting
10/27/2021, 10:57:39 PMVivint BridgeLoaded plugin '@balansse/homebridge-vivint'
10/27/2021, 10:57:39 PMVivint BridgeLoading 1 platforms...
10/27/2021, 10:57:40 PMVivint BridgeBridge is running on port 53826.
```

When I run "vivint_mfa_cli_debug", this is what I get:

$ vivint_mfa_cli_debug
Please enter your Vivint login email: tucker.aaron1923@gmail.com
Please enter your Vivint login password: Password
StatusCodeError: 403 - "error code: 1020"
    at new StatusCodeError (/usr/lib/node_modules/vivint_mfa_cli_debug/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/lib/node_modules/vivint_mfa_cli_debug/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/vivint_mfa_cli_debug/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/lib/node_modules/vivint_mfa_cli_debug/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (/usr/lib/node_modules/vivint_mfa_cli_debug/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:400:28)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/vivint_mfa_cli_debug/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35) {
  statusCode: 403,
  error: 'error code: 1020',
  options: {
    method: 'POST',
    url: 'https://www.vivintsky.com/api/login',
    body: {
      username: 'tucker.aaron1923@gmail.com',
      password: 'PasswordChanged',
      persist_session: true
    },
    json: true,
    resolveWithFullResponse: true,
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    transform2xxOnly: false
  },
  response: <ref *1> IncomingMessage {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: true,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      errored: null,
      closed: false,
      closeEmitted: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: true,
      dataEmitted: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    _events: [Object: null prototype] {
      end: [Array],
      close: [Array],
      data: [Function (anonymous)],
      error: [Function (anonymous)]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'www.vivintsky.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'www.vivintsky.com',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 115,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: true,
    headers: {
      date: 'Thu, 28 Oct 2021 03:33:51 GMT',
      'content-type': 'text/plain; charset=UTF-8',
      'content-length': '16',
      connection: 'close',
      'x-frame-options': 'SAMEORIGIN',
      'referrer-policy': 'same-origin',
      'cache-control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
      expires: 'Thu, 01 Jan 1970 00:00:01 GMT',
      'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
      'set-cookie': [Array],
      server: 'cloudflare',
      'cf-ray': '6a511ae5bf73295c-ORD'
    },
    rawHeaders: [
      'Date',
      'Thu, 28 Oct 2021 03:33:51 GMT',
      'Content-Type',
      'text/plain; charset=UTF-8',
      'Content-Length',
      '16',
      'Connection',
      'close',
      'X-Frame-Options',
      'SAMEORIGIN',
      'Referrer-Policy',
      'same-origin',
      'Cache-Control',
      'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
      'Expires',
      'Thu, 01 Jan 1970 00:00:01 GMT',
      'Expect-CT',
      'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
      'Set-Cookie',
      '__cf_bm=HL8xqtYhZlzkUvlqtiF_LQDwWDDUeuuOFVHsCZRO310-1635392031-0-ASttPObTSd48JiwogSm/9Z5BdU8pIyrvN/AOkgD9SwA8fxZO03oHWRq31JuhcR79Vy9E1mQeQHh9t4Ia6QZocEQ=; path=/; expires=Thu, 28-Oct-21 04:03:51 GMT; domain=.vivintsky.com; HttpOnly; Secure',
      'Server',
      'cloudflare',
      'CF-RAY',
      '6a511ae5bf73295c-ORD'
    ],
    trailers: {},
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: '',
    method: null,
    statusCode: 403,
    statusMessage: 'Forbidden',
    client: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'www.vivintsky.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'www.vivintsky.com',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 115,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _consuming: false,
    _dumped: false,
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'POST /api/login HTTP/1.1\r\n' +
        'host: www.vivintsky.com\r\n' +
        'accept: application/json\r\n' +
        'content-type: application/json\r\n' +
        'content-length: 91\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/login',
      _ended: true,
      res: [Circular *1],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'www.vivintsky.com',
      protocol: 'https:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    request: Request {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      method: 'POST',
      body: '{"username":"tucker.aaron1923@gmail.com","password":"PasswordChangedforPrivacy","persist_session":true}',
      resolveWithFullResponse: true,
      readable: true,
      writable: true,
      explicitMethod: true,
      _qs: [Querystring],
      _auth: [Auth],
      _oauth: [OAuth],
      _multipart: [Multipart],
      _redirect: [Redirect],
      _tunnel: [Tunnel],
      _rp_resolve: [Function (anonymous)],
      _rp_reject: [Function (anonymous)],
      _rp_promise: [Promise],
      _rp_callbackOrig: undefined,
      callback: [Function (anonymous)],
      _rp_options: [Object],
      headers: [Object],
      setHeader: [Function (anonymous)],
      hasHeader: [Function (anonymous)],
      getHeader: [Function (anonymous)],
      removeHeader: [Function (anonymous)],
      localAddress: undefined,
      pool: {},
      dests: [],
      __isRequestRequest: true,
      _callback: [Function: RP$callback],
      uri: [Url],
      proxy: null,
      tunnel: true,
      setHost: true,
      originalCookieHeader: undefined,
      _disableCookies: true,
      _jar: undefined,
      port: 443,
      host: 'www.vivintsky.com',
      path: '/api/login',
      _json: true,
      httpModule: [Object],
      agentClass: [Function: Agent],
      agent: [Agent],
      _started: true,
      href: 'https://www.vivintsky.com/api/login',
      req: [ClientRequest],
      ntick: true,
      response: [Circular *1],
      originalHost: 'www.vivintsky.com',
      originalHostHeaderName: 'host',
      responseContent: [Circular *1],
      _destdata: true,
      _ended: true,
      _callbackCalled: true,
      [Symbol(kCapture)]: false
    },
    toJSON: [Function: responseToJSON],
    caseless: Caseless { dict: [Object] },
    body: 'error code: 1020',
    [Symbol(kCapture)]: false,
    [Symbol(RequestTimeout)]: undefined

**Comment by Ooblek33** [comment] 2021-10-29 22:14
I uninstalled the hoobs app, then downloaded the latest from the website.  After downloading 4.1.11 on my Mac and then installing the app, the version reads 4.0.100 and gets stuck on the update process.  I also cannot install any plugins as I get an error for any plugin I select.  I have tried to download the app several times and have restarted my Mac with no results.  Any advice?

**Comment by mkellsy** [comment] 2021-10-31 00:59
Duplicate of https://github.com/hoobs-org/sidecars/issues/4
Fix instructions in this issue

**Closed by mkellsy** 2021-10-31 00:59 UTC
Labels: plugins, discovery
