### ISSUE TITLE
Plugin Type Not Detected

### ISSUE THREAD

**Issue by askovi** [hoobs-org/HOOBS#200] opened 2019-10-13 02:11 UTC
I installed the Ring plugin from the list and when it was done it brought me to /config/ring but it's empty: 
![image](https://user-images.githubusercontent.com/3981552/66709980-33d69680-ed3d-11e9-96ad-2bab3fdc7961.png)

I tried refreshing but still nothing. No error in console.

**Comment by mkellsy** [comment] 2019-10-13 06:01
This is caused by not finding the plugin type.

1. I need to find out why the code parse isn't working
2. If there is schema files, use them first
3. Default the plug-in type to both, so if the parsing doesn't work it will show up

**Comment by mkellsy** [comment] 2019-10-13 23:52
I had to include the default export when running a plugin. I also had to load hap-nodejs into the dummy homebridge object.

Not the plugins can start to load before calling the rigged register functions.

Fixed in 3.0.0-beta.68

**Closed by mkellsy** 2019-10-13 23:52 UTC
Labels: 3.0.0, bug
