### ISSUE TITLE
Just got my Hoobs box less than a week

### ISSUE THREAD

**Issue by debratton** [hoobs-org/HOOBS#972] opened 2020-12-17 15:01 UTC
I cannot get to http://hoobs.local any longer.  I was searching for answers and one suggestion was to ssh hoobs@hoobs.local and that doesn't work as well.  On the day I received I added to Homekit, installed certified myQ plugin and Ring, nothing else and it has worked great until I noticed myQ garage wasn't responding in Homekit.  How do I fix this?

**Comment by debratton** [comment] 2020-12-17 15:45
So to add on.  I have resolved some of my issues.  I found the ip from my cable modem and was able to access by ip.  It appears myQ had an update.  Is that normally what happens if a plugin has an update it stops working until you update?  I am still unable to get to http://hoobs.local which isn't the end of the world but why did it work for a week and now it doesn't work? I found somewhere that some routers don't like the .local, but as I mentioned it worked for a week.

I had 100's of these in log until I updated
12/17/2020, 9:19:00 AM [myQ] myQ API: Unable to authenticate. Will retry later.
12/17/2020, 9:19:03 AM [myQ] myQ API: Connection has been reset.
12/17/2020, 9:19:03 AM [myQ] myQ API: Unable to authenticate. Will retry later.

12/17/2020, 9:19:09 AM Plugin "homebridge-myq" updated.
12/17/2020, 9:19:09 AM Got SIGINT, shutting down Bridge...
12/17/2020, 9:19:09 AM [myQ] myQ API: Connection has been reset.
12/17/2020, 9:19:09 AM [myQ] myQ API: Unable to authenticate. Will retry later.
12/17/2020, 9:19:16 AM Loaded plugin 'homebridge-myq'
12/17/2020, 9:19:16 AM [12/17/2020, 8:19:16 AM] Registering platform 'homebridge-myq.myQ'
12/17/2020, 9:19:18 AM Loaded plugin 'homebridge-ring'
12/17/2020, 9:19:18 AM Loading 2 platforms...
12/17/2020, 9:19:18 AM [12/17/2020, 8:19:18 AM] Registering platform 'homebridge-ring.Ring'
12/17/2020, 9:19:18 AM [myQ] Initializing myQ platform...
12/17/2020, 9:19:18 AM [Ring] Initializing Ring platform...
12/17/2020, 9:19:18 AM [Ring] Configuring cached accessory 00000000-0000-0000-0000-000000000000 Ring
12/17/2020, 9:19:18 AM [Ring] Configuring cached accessory 00000000-0000-0000-0000-000000000000 RingBackyard
12/17/2020, 9:19:18 AM [Ring] Configuring cached accessory 00000000-0000-0000-0000-000000000000 RingChime
12/17/2020, 9:19:18 AM Bridge is running on port 00000.
12/17/2020, 9:19:18 AM [myQ] myQ API: Successfully connected to the myQ API.
12/17/2020, 9:19:19 AM

**Comment by askovi** [comment] 2020-12-17 19:45
The myQ plugin had an issue caused by the myQ API which is what caused it to stop working. This was fixed in the latest update. 

Regarding .local your browser may have cached the DNS for the previous local ip. Try opening a private browsing window and see if that works. Otherwise you can also try just http://hoobs with no domain.

**Comment by GeoTC** [comment] 2020-12-23 22:07
I have a new hoobs out of the box.  Cannot get into it.  App does network scan and not there.  Tried IP address, just hoobs (no local).  Tried on iPhone and Mac.  No luck

**Closed** 2021-01-30 10:39 UTC
Labels: wontfix
