### ISSUE TITLE
Error: Invalid IV length

### ISSUE THREAD

**Issue by fabr85** [hoobs-org/HOOBS#690] opened 2020-06-11 16:53 UTC
**Description**
Hoobs stopped

**Version**
latest

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [x ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
11.6.2020, 18:44:45 Error: Invalid IV length
    at Cipheriv.createCipherBase (internal/crypto/cipher.js:79:18)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:115:20)
    at new Cipheriv (internal/crypto/cipher.js:217:22)
    at Object.createCipheriv (crypto.js:109:10)
    at Object.chacha20_poly1305_encryptAndSeal (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/util/hapCrypto.js:79:35)
    at HAPServer._this._handlePairVerifyStepOne (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:486:39)
    at HAPServer._this._handlePairVerify (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:450:23)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:227:39)
    at IncomingMessage.emit (events.js:198:13)
    at endReadableNT (_stream_readable.js:1129:12)
11.6.2020, 18:44:45 Error: Invalid IV length
```

**Additional context**

**Comment by askovi** [comment] 2020-06-11 17:40
Duplicate of solved issue: https://github.com/hoobs-org/HOOBS/issues/649

**Closed by askovi** 2020-06-11 17:40 UTC
Labels: bug, discovery
