### ISSUE TITLE
System backup timeouts, never completes

### ISSUE THREAD

**Issue by jqnatividad** [hoobs-org/HOOBS#454] opened 2020-01-29 17:14 UTC
**Description**
Pressing the System option in the backup doesn't complete.  It seems to timeout.  Configuration and Log backup works without issues.

**Version**
HOOBS 3.1.20

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [X] No

**Previous version**
N/A. Fresh install

**Did you originally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [X] Custom Install

**If this is a custom install, what's your operating system?**
Used HOOBS image running on RPI 3 1GB mem

**List your plugins**
         "nest",
        "homebridge-harmony",
        "homebridge-bond",
        "homebridge-weather-plus",
        "homebridge-people-x",
        "homebridge-camera-ffmpeg",
        "homebridge-nest-cam2",
        "homebridge-roomba-stv",
        "homebridge-script2",
        "homebridge-delay-switch"

**Additional context**
All my plugins work without problems, that's why I want to take a backup.

**Comment by mkellsy** [comment] 2020-01-29 19:46
Logs?

I wondering if the zip file is running out of memory.

**Comment by jqnatividad** [comment] 2020-01-29 21:37
It’s a brand new 128G SSD, so there’s plenty of space.

I’ll attach logs later when I get home.

**Comment by jqnatividad** [comment] 2020-02-06 22:18
Sorry it took a while... here's the log with debug mode on....

[hoobs-detailedlog.txt](https://github.com/hoobs-org/HOOBS/files/4167984/hoobs-detailedlog.txt)

Note I started the system backup 9:31am (line 2070) and it just kept going and never returned...

**Comment by mkellsy** [comment] 2020-02-10 22:13
Duplicate of #473

**Closed by mkellsy** 2020-02-10 22:13 UTC
Labels: bug, discovery, tracked
