### ISSUE TITLE
Harmony 1.3.8

### ISSUE THREAD

**Issue by Christian-CFP** [hoobs-org/HOOBS#637] opened 2020-05-21 17:31 UTC
Harmony 1.3.8 requires homebridge > 1.0.4.

This error happens:
21.5.2020, 19:15:14 (node:3719) UnhandledPromiseRejectionWarning: TypeError: AccessControlManagement is not a constructor
21.5.2020, 19:15:14 at HarmonySubPlatform.readTVAccessories (/home/hoobs/.hoobs/node_modules/homebridge-harmony/harmonySubPlatform.js:291:23)
21.5.2020, 19:15:14 at HarmonySubPlatform.readAccessories (/home/hoobs/.hoobs/node_modules/homebridge-harmony/harmonySubPlatform.js:158:58)
21.5.2020, 19:15:14 at /home/hoobs/.hoobs/node_modules/homebridge-harmony/harmonyBase.js:93:27
21.5.2020, 19:15:14 (node:3719) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
21.5.2020, 19:15:14 (node:3719) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

What homebridge version runs on HOOBS 3.2.4?
And can you update it when lower?

**Comment by BobbySlope** [comment] 2020-05-21 18:13
duplicate of #636 closing this and work on at #636

**Comment by b-** [comment] 2020-05-21 18:24
https://github.com/homebridge/HAP-NodeJS/blob/8ce43281b637fd1fb636436c3d60352dec54ba14/src/lib/tv/AccessControlManagement.ts

**Comment by b-** [comment] 2020-05-21 18:25
It’s failing on integration with AccessControlManagement

**Closed** 2020-05-21 18:49 UTC
Labels: discovery, plugins

**Comment by Christian-CFP** [comment] 2020-05-21 20:00
Awesome!
