### ISSUE TITLE
Ring Hoobs certified plugin in issues

### ISSUE THREAD

**Issue by adavison007** [hoobs-org/HOOBS#322] opened 2019-12-14 15:22 UTC
**Description**
If you configure the ring features via the UI some work, some don't the one I know definitely does not work is Motion.... so If I set "Hide Motion Sensors" to false, they do not appear... If I leave it blank and delete that line in the JSON, they do appear.

The Ring Cameras, motion sensors and light switches also do not appear as accessories in hoobs

**Expected behavoir**
Motion tiles should appear

Devices should appear in hoobs ui

**Plugin name**
Homebridge-Ring @hoobs

**Please report the issue to the plugin developer**
Done

**Version**
3.1.1
**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [X
<img width="807" alt="Untitled 2" src="https://user-images.githubusercontent.com/47482260/70850734-97885780-1e85-11ea-8d6d-74c283c271c3.png">
 ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
POST CONFIG HERE
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment] 2019-12-16 15:58
Duplicate of #307, moved

**Closed by mkellsy** 2019-12-16 15:58 UTC
Labels: discovery, plugins
