### ISSUE TITLE
Multiple Homebridge instances - /var/hoobs/.instance - variable?

### ISSUE THREAD

**Issue by nicoh88** [hoobs-org/HOOBS#485] opened 2020-02-20 09:36 UTC
**Description**
When create the second instance, as described [here](https://github.com/hoobs-org/HOOBS/issues/218#issuecomment-576705263): **EADDRINUSE**

I think, the variable of "name for the cluster instance" is not used properly.

```
ls -lsa /var/hoobs/
insgesamt 12
4 drwxr-xr-x  3 root root 4096 Feb 20 10:16 .
4 drwxr-xr-x 13 root root 4096 Feb 20 10:10 ..
4 drwxr-xr-x  2 root root 4096 Feb 20 10:22 .instance
```

**Version**
```
hoobs --version
3.1.20
```

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [x] No, fresh install

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
```
cat /etc/debian_version
10.2
uname -a
Linux raspberrypi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
```

**List your plugins**
Nothing.

**Post your log**
You can get the log from the intercafe. This is in the Log section.

`wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --instance`

```
...
> @hoobs/hoobs@3.1.20 postinstall /usr/local/lib/node_modules/@hoobs/hoobs
> bin/hoobs upgrade

+ @hoobs/hoobs@3.1.20
added 304 packages from 217 contributors in 73.083s
```

`sudo hoobs cluster client`

```
prompt: Choose your HOOBS cluster account name:  (Administrator)
prompt: Choose your HOOBS cluster username:  (admin)
prompt: Choose your HOOBS cluster password: Test1234#
prompt: Confirm your password:
  Installing Prerequisites
  Installing NGINX
  Configuring NGINX
  Installing NGINX Service
  Synchronizing state of nginx.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable nginx
  Installing NGINX Service
  Creating HOOBS User
  Installing HOOBS Service
Created symlink /etc/systemd/system/multi-user.target.wants/hoobs.service → /etc/systemd/system/hoobs.service.
```

`journalctl -u hoobs.service -n20 -f`

```
Feb 20 10:10:54 raspberrypi systemd[1]: Started HOOBS.
Feb 20 10:10:55 raspberrypi hoobs[11358]: - Enviornment
Feb 20 10:10:55 raspberrypi hoobs[11358]: - Migrating
Feb 20 10:10:56 raspberrypi hoobs[11358]: - Plugins
Feb 20 10:10:56 raspberrypi hoobs[11358]: - Modules
Feb 20 10:11:07 raspberrypi hoobs[11358]: - Clear Migration
Feb 20 10:11:07 raspberrypi sudo[11374]:    hoobs : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/rm -fR /var/hoobs/.migration
Feb 20 10:11:07 raspberrypi sudo[11374]: pam_unix(sudo:session): session opened for user root by (uid=0)
Feb 20 10:11:07 raspberrypi sudo[11374]: pam_unix(sudo:session): session closed for user root
Feb 20 10:11:07 raspberrypi hoobs[11358]: - Application
Feb 20 10:11:08 raspberrypi sudo[11383]:    hoobs : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/systemctl restart nginx.service
Feb 20 10:11:08 raspberrypi sudo[11383]: pam_unix(sudo:session): session opened for user root by (uid=0)
Feb 20 10:11:09 raspberrypi sudo[11383]: pam_unix(sudo:session): session closed for user root
Feb 20 10:11:12 raspberrypi hoobs[11358]: [2020-2-20 10:11:12] HOOBS listning on port 8080.
```

`sudo hoobs cluster create`

```
prompt: Enter a name for the cluster instance:  01
prompt: Enter the port this cluster instance will run on:  (52827) 52820
prompt: Enter your HOOBS username:  admin
prompt: Enter your HOOBS password:
prompt: Enter the bridge port for Homebridge:  (52826) 52830
prompt: Enter the URL of the cluster client:  (http://hoobs.local:8080) http://localhost:8080
  Installing Prerequisites
  Installing HOOBS Service
Created symlink /etc/systemd/system/multi-user.target.wants/hoobs.01.service → /etc/systemd/system/hoobs.01.service.
```

`journalctl -u hoobs.01.service -n20 -f`

```
Feb 20 10:13:53 raspberrypi systemd[1]: Started HOOBS.
Feb 20 10:13:54 raspberrypi hoobs[11591]: - Enviornment
Feb 20 10:13:57 raspberrypi sudo[11608]:    hoobs : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/rm -fR /var/hoobs/.instance
Feb 20 10:13:57 raspberrypi sudo[11608]: pam_unix(sudo:session): session opened for user root by (uid=0)
Feb 20 10:13:58 raspberrypi sudo[11608]: pam_unix(sudo:session): session closed for user root
Feb 20 10:13:58 raspberrypi hoobs[11591]: [2020-2-20 10:13:58] HOOBS listning on port 52820.
Feb 20 10:13:59 raspberrypi hoobs[11591]: [Homebridge] [2020-2-20 10:13:59] Loaded config.json with 0 accessories and 0 platforms.
Feb 20 10:14:00 raspberrypi hoobs[11591]: [Homebridge] [2020-2-20 10:14:00] No plugins found.
Feb 20 10:14:00 raspberrypi hoobs[11591]: [Homebridge] [2020-2-20 10:14:00] Loading 0 platforms...
Feb 20 10:14:00 raspberrypi hoobs[11591]: [Homebridge] [2020-2-20 10:14:00] Loading 0 accessories...
Feb 20 10:14:00 raspberrypi hoobs[11591]: [Homebridge] [2020-2-20 10:14:00] API launched
Feb 20 10:14:00 raspberrypi hoobs[11591]: [Homebridge] [2020-2-20 10:14:00] Service is running on port 52830.
```

**Works so far.** 🎉 

---

Then seconds instance "_02_"

`sudo hoobs cluster create`

```
prompt: Enter a name for the cluster instance:  02
prompt: Enter the port this cluster instance will run on:  (52827) 52821
prompt: Enter your HOOBS username:  admin
prompt: Enter your HOOBS password:
prompt: Enter the bridge port for Homebridge:  (52826) 52831
prompt: Enter the URL of the cluster client:  (http://hoobs.local:8080) http://localhost:8080
  Installing Prerequisites
  Installing HOOBS Service
Created symlink /etc/systemd/system/multi-user.target.wants/hoobs.02.service → /etc/systemd/system/hoobs.02.service.
```

`journalctl -u hoobs.02.service -n20 -f`

```
Feb 20 10:18:30 raspberrypi systemd[1]: Started HOOBS.
Feb 20 10:18:31 raspberrypi hoobs[12233]: - Enviornment
Feb 20 10:18:34 raspberrypi hoobs[12233]: [2020-2-20 10:18:34] listen EADDRINUSE: address already in use :::52820
Feb 20 10:18:34 raspberrypi hoobs[12233]: Error: listen EADDRINUSE: address already in use :::52820
Feb 20 10:18:34 raspberrypi hoobs[12233]:     at Server.setupListenHandle [as _listen2] (net.js:1306:16)
Feb 20 10:18:34 raspberrypi hoobs[12233]:     at listenInCluster (net.js:1354:12)
Feb 20 10:18:34 raspberrypi hoobs[12233]:     at Server.listen (net.js:1442:7)
Feb 20 10:18:34 raspberrypi hoobs[12233]:     at Function.serverListen [as listen] (/home/hoobs/.hoobs/node_modules/express-ws/lib/index.js:42:40)
Feb 20 10:18:34 raspberrypi hoobs[12233]:     at API.start (/home/hoobs/.hoobs/lib/api.js:157:17)
Feb 20 10:18:34 raspberrypi hoobs[12233]:     at module.exports (/home/hoobs/.hoobs/lib/cli.js:123:21)
Feb 20 10:18:34 raspberrypi hoobs[12233]:     at processTicksAndRejections (internal/process/task_queues.js:94:5)
Feb 20 10:18:34 raspberrypi hoobs[12233]: [HOOBS] Stopping server.
Feb 20 10:18:34 raspberrypi systemd[1]: hoobs.02.service: Main process exited, code=exited, status=1/FAILURE
Feb 20 10:18:34 raspberrypi systemd[1]: hoobs.02.service: Failed with result 'exit-code'.
Feb 20 10:18:37 raspberrypi systemd[1]: hoobs.02.service: Service RestartSec=3s expired, scheduling restart.
Feb 20 10:18:38 raspberrypi systemd[1]: hoobs.02.service: Scheduled restart job, restart counter is at 13.
Feb 20 10:18:38 raspberrypi systemd[1]: Stopped HOOBS.
```

```
ls -lsa /var/hoobs/
insgesamt 12
4 drwxr-xr-x  3 root root 4096 Feb 20 10:16 .
4 drwxr-xr-x 13 root root 4096 Feb 20 10:10 ..
4 drwxr-xr-x  2 root root 4096 Feb 20 10:22 .instance
```

```
ls -lsa /var/hoobs/.instance/
insgesamt 12
4 drwxr-xr-x 2 root root 4096 Feb 20 10:22 .
4 drwxr-xr-x 3 root root 4096 Feb 20 10:16 ..
4 -rwxr-xr-x 1 root root  202 Feb 20 10:22 config.json
```

```
ls -lsa /home/hoobs/.hoobs/etc
insgesamt 28
4 drwxr-xr-x 3 hoobs hoobs 4096 Feb 20 10:15 .
4 drwxr-xr-x 6 hoobs hoobs 4096 Feb 20 10:11 ..
4 -rwxr-xr-x 1 hoobs hoobs  352 Feb 20 10:10 access.json
4 -rw-r--r-- 1 hoobs hoobs  748 Feb 20 10:13 config.json
4 -rw-r--r-- 1 hoobs hoobs  810 Feb 20 10:15 dashboard.json
4 -rw-r--r-- 1 hoobs hoobs    2 Feb 20 10:11 layout.json
4 drwxr-xr-x 4 hoobs hoobs 4096 Feb 20 10:42 nstance
```

```
ls -lsa /home/hoobs/.hoobs/etc/nstance/
insgesamt 28
4 drwxr-xr-x 4 hoobs hoobs 4096 Feb 20 10:42 .
4 drwxr-xr-x 3 hoobs hoobs 4096 Feb 20 10:15 ..
4 -rw-r--r-- 1 hoobs hoobs  352 Feb 20 10:42 access.json
4 drwxr-xr-x 2 hoobs hoobs 4096 Feb 20 10:13 accessories
4 -rw-r--r-- 1 hoobs hoobs  645 Feb 20 10:17 config.json
4 -rw-r--r-- 1 hoobs hoobs    2 Feb 20 10:13 layout.json
4 drwxr-xr-x 2 hoobs hoobs 4096 Feb 20 10:14 persist
```

I think the directory should be called "_01.instance_" and "_02.instance_".

---

**BTW:** Spelling mistakes? (missing "i")

![Bildschirmfoto 2020-02-20 um 10 35 16](https://user-images.githubusercontent.com/264264/74920655-cd3d4580-53cc-11ea-9962-b14838272109.jpg)

**Comment by nicoh88** [comment] 2020-02-27 12:17
Guys? Any news?

**Comment by mkellsy** [comment] 2020-02-28 04:04
We are rebuilding the Docker image soon. We have some work to do on it.

**Comment by nicoh88** [comment] 2020-02-28 08:01
@mkellsy 

Cool! Thanks.

But, docker image doesn't help me, i have a debian server and use the npm-package.

**Comment by mkellsy** [comment] 2020-02-28 16:09
If you are installing for instances you can run this command to stop the auto service install
```
wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --instance
```

If you already have the default instance installed you need to run this before setting up instances
```
sudo hoobs service install
```

Then setup the client
```
sudo hoobs cluster client
```

Then you can add as many instances as you need
```
sudo hoobs cluster create
```

**Comment by nicoh88** [comment] 2020-02-28 17:15
😕 Is it now fixed? So I did it! See the first post, please. Thanks

**Comment by mkellsy** [comment] 2020-02-29 09:33
Instances will run under a folder with the instance name.

**Comment by nicoh88** [comment] 2020-02-29 10:23
WTF?

Please read the first post in this issue! It is a bug! You can it reproduce.

**Comment by mkellsy** [comment] 2020-03-01 01:56
HOOBS instances run under `~/.hoobs/`. The folders and files in `/var/hoobs/` are used to store information before the new instance init. It looks like this is not getting removed after initialization.

This could be happening because you have a password on sudo.
1. In /etc/sudoers add `NOPASSWD` to the admin group. https://github.com/hoobs-org/HOOBS/wiki/2.5.2-Debian-Installation#sudo
or
2. Modify the .service files to include this flag `-p 'your sudo password'` the `ExecStart=`

WORKAROUND
After you start each instance run this command `sudo rm -fR /var/hoobs/.instance` or manually edit the congig.json files in `~/.hoobs/etc/01` and `~/.hoobs/etc/02`.

NOTES
If you run a `ls -la ~/.hoobs/etc/` you should see a folder for each instance. And the `config.json` in the root is for the client.

If you could, run this `ls -la /etc/systemd/system/` There should be a service defined for the client `hoobs.service` then there should be a service for each instance `hoobs.[instance name].service` (`hoobs.01.service` and `hoobs.02.service`). These are the services you would need to add the `-p 'your sudo password'` to.

**Comment by mkellsy** [comment] 2020-03-01 03:50
I found the cause. I was able to reproduce by creating the instances faster then they can init. I have a fix for this coming in 3.1.21

**Comment by anschroe** [comment] 2020-03-01 18:04
I'm having [similar issues](https://www.reddit.com/r/HOOBS/comments/fbpcg5/stuck_setting_up_multiple_instances/) - will look forward to 3.1.21!

**Comment by nicoh88** [comment] 2020-03-02 08:02
NOT FIXED WITH 3.1.22 😡

--

Uninstall
```
npm -g uninstall @hoobs/hoobs
userdel --remove hoobs
rm -Rf /var/hoobs
rm /etc/systemd/system/multi-user.target.wants/hoobs*
rm /etc/systemd/system/hoobs*
apt purge nginx
```

--

Install 3.1.21
```
wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --instance
sudo hoobs cluster client
# instance 01
sudo hoobs cluster create
# instance 02
sudo hoobs cluster create
```

--

No folder with name `01` or `02` in `~/.hoobs/etc/`.

--

```
ls -ls /home/hoobs/.hoobs/etc/
insgesamt 16
4 -rwxr-xr-x 1 hoobs hoobs  352 Mär  2 08:52 access.json
4 -rw-r--r-- 1 hoobs hoobs  674 Mär  2 08:52 config.json
4 -rw-r--r-- 1 hoobs hoobs    2 Mär  2 08:52 layout.json
4 drwxr-xr-x 2 hoobs hoobs 4096 Mär  2 08:55 nstance
```

--

Systemd service files in `/etc/systemd/system/` are okay.

**Comment by mkellsy** [comment] 2020-03-02 08:04
Try naming them "one" and "two" there is a file name normalization logic that might be removing the numbers.

**Comment by nicoh88** [comment] 2020-03-02 08:14
Doesn't work!

```
root@raspberrypi ~ # ls -lsa /etc/systemd/system/hoobs*
4 -rwxr-xr-x 1 root root 240 Mär  2 09:12 /etc/systemd/system/hoobs.a.service
4 -rwxr-xr-x 1 root root 240 Mär  2 09:13 /etc/systemd/system/hoobs.b.service
4 -rwxr-xr-x 1 root root 212 Mär  2 09:11 /etc/systemd/system/hoobs.service
```

```
root@raspberrypi ~ # ls -ls /home/hoobs/.hoobs/etc/
insgesamt 16
4 -rwxr-xr-x 1 hoobs hoobs  352 Mär  2 09:11 access.json
4 -rw-r--r-- 1 hoobs hoobs  674 Mär  2 09:11 config.json
4 -rw-r--r-- 1 hoobs hoobs    2 Mär  2 09:11 layout.json
4 drwxr-xr-x 2 hoobs hoobs 4096 Mär  2 09:13 nstance
```

**Comment by mkellsy** [comment] 2020-03-02 08:19
I'm testing it again on my Debian VM.

**Comment by mkellsy** [comment] 2020-03-02 08:42
I found the issue.

WORKAROUND
Edit each of your services.
```
sudo nano /etc/systemd/system/hoobs.a.service
```

Edit the `ExecStart` and add the second "-" to the --instance flag.
```
ExecStart=/usr/local/bin/hoobs server --instance '02'
```

After run this command
```
sudo systemctl daemon-reload
```
and then reboot or restart the services
```
sudo systemctl restart hoobs
sudo systemctl restart hoobs.01
sudo systemctl restart hoobs.02
```

**Comment by mkellsy** [comment] 2020-03-02 08:54
Fixed and released in 3.1.22

**Comment by nicoh88** [comment] 2020-03-02 09:18
[Workaround](https://github.com/hoobs-org/HOOBS/issues/485#issuecomment-593286007) works!

**Comment by anschroe** [comment] 2020-03-14 20:10
I'm thinking this is less of a Hoobs issue and more of a configuration issue on my part. I'm able to get the client and instances installed as described, but the whole thing goes to crap once I update the config files. To make sure I'm interpreting the wiki correctly, I setup the cluster and client config files as follows:

Cluster
The server block in the cluster config file corresponds to the web ui port(e.g. 8080). The client block points to the IP addresses and ports of the instances. In my case, they're on the same device so I just need the port numbers to be different and correspond to what I assigned in the client setup. The cluster config has no bridge information or home setup ID

Client
The client config server block uses the same port that I entered as an instance on the cluster config. The home setup ID will autopopulate ("X-HM://"). The client block is the web ui url as specified in the cluster config (e.g. 8080). The bridge needs a unique name, port number and username for each instance.

Is there anything I'm doing wrong here? Once I restart everything the web UI fails to load. I can access in terminal but even then can't figure out how to load plug-ins into the instances. thanks!

**Comment by mkellsy** [comment] 2020-03-14 23:40
The client (UI) runs on port 8080. The instances each run on different ports.
The client and each instance has their own config.json file.

Client (UI) = ~/.hoobs/etc/config.json
Instances = ~/.hoobs/etc/[instance name]/config.json

You should be using the client (UI) to configure. It will keep everything straight for you.

**Comment by anschroe** [comment] 2020-03-15 04:14
Hmm...I'm not seeing where things would be configured in the client (UI).  tThere is no "dropdown" that I can find.

**Comment by mkellsy** [comment] 2020-03-15 06:50
Upper right of the screen in the header

**Comment by anschroe** [comment] 2020-03-15 15:30
Still no dice.  There has got to be something really simple I'm overlooking, but for the life of me, I can't figure it out.  Both instances show up as installed and enabled, but there is nothing different in the UI to add the config info to.  Thanks in advance - I appreciate your patience

**Comment by mkellsy** [comment] 2020-03-15 19:01
If you started with a default HOOBS install there already is a default instance running. To do this you will need to use an SSH terminal.

First stop and disable HOOBS
```
sudo hoobs service stop
sudo hoobs service disable
```

Then delete the `~/.hoobs` folder and the `hoobs.service`
```
rm -fR ~/.hoobs
sudo rm -f /etc/systemd/system/hoobs.service
```

Then setup the client. (Follow the prompts)
```
sudo hoobs cluster client
```

Then setup each instance (Follow the prompts)
```
sudo hoobs cluster create
```

Now you will be able to access the UI on port 8080 or whatever port you used for the client setup.

**Comment by anschroe** [comment] 2020-03-17 03:50
Thank you!  Was not deleting the Hoobs service previously.  Pretty slick implementation once I got it up and running.

**Closed** 2020-03-17 15:37 UTC
Labels: bug, discovery, tracked
