### ISSUE TITLE
Updated Hoobs OS and Nest Plugins and now Bridge service will not run. 

### ISSUE THREAD

**Issue by maswind** [hoobs-org/HOOBS#685] opened 2020-06-07 01:46 UTC
I updated to Hoobs Version 3.2.6 without incident. I just updated the two plugins for my Nest doorbell and thermostat, and now I keep getting a bridge not running error. I have powered the Pi that Hoobs is running on several times without success. Before updating the plug ins, Hoobs was running great.

**Comment by askovi** [comment] 2020-06-07 01:48
Please follow the bug report template and provide all the required information

**Comment by maswind** [comment] 2020-06-07 02:12
**Description**

I've installed the update to Hoobs Version 3.2.6 which was successful. I then updated the plugins for my East doorbell and thermostat as each stated that the plugin had an update. After the update of the plugins, Hoobs will not run, and when hitting restart, the same problem occurs. 

**Version**
3.2.6

Did you upgrade
Yes

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**

No.

**Did you perform an upgrade from HOOBS 2.1.1? Some things are different.**

No

**What device are you using?
Please let us know the device you are running HOOBS on**.

Custom Install

**If this is a custom install, what's your operating system?**

RasperryPi 4

**List your plugins**

Nest
Nest Cam

**Post your config.**

{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY46NC",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hunters-green",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "92629"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "40:F1:66:BA:F9:A8"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Nest",
            "plugin_map": {
                "plugin_name": "homebridge-nest"
            },
            "access_token": "XXXX",
            "primary_phone": "XXXX",
            "name": "Nest"
        },
        {
            "platform": "Nest-cam",
            "access_token": "XXXX",
            "primary_phone": "XXXX",
            "plugin_map": {
                "plugin_name": "homebridge-nest-cam"
            }
        }
    ]
}

**Post Your Log.** 

6/6/2020, 6:40:29 PM HOOBS listening on port 8080.
6/6/2020, 6:40:31 PM Loaded plugin "homebridge-nest".
6/6/2020, 6:40:31 PM Loaded plugin "homebridge-nest-cam".
6/6/2020, 6:40:31 PM [Nest] Fetching Nest devices.
6/6/2020, 6:40:31 PM TypeError: Cannot read property 'issueToken' of undefined
    at new NestCamPlatform (/home/hoobs/.hoobs/node_modules/homebridge-nest-cam/dist/index.js:42:45)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:283:34)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:86:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
6/6/2020, 6:40:31 PM Got SIGTERM, shutting down Bridge...
6/6/2020, 6:40:44 PM Loaded plugin "homebridge-nest".
6/6/2020, 6:40:44 PM Loaded plugin "homebridge-nest-cam".
6/6/2020, 6:40:44 PM [Nest] Fetching Nest devices.
6/6/2020, 6:40:44 PM TypeError: Cannot read property 'issueToken' of undefined
    at new NestCamPlatform (/home/hoobs/.hoobs/node_modules/homebridge-nest-cam/dist/index.js:42:45)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:283:34)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:86:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
6/6/2020, 6:40:44 PM Got SIGTERM, shutting down Bridge...
6/6/2020, 6:40:58 PM [Nest] initing thermostat "Hallway Thermostat": deviceId: 09AA01AC1717082R structureId: 6dcb3130-e1d7-11e6-a6ca-22000b519123
6/6/2020, 6:40:58 PM [Nest] initing home_away_sensor "Home Occupied": deviceId: 6dcb3130-e1d7-11e6-a6ca-22000b519123 structureId: 6dcb3130-e1d7-11e6-a6ca-22000b519123
6/6/2020, 6:40:58 PM [Nest] initing temp_sensor "Bedroom": deviceId: 18B430CBF9FF6FC8 structureId: 6dcb3130-e1d7-11e6-a6ca-22000b519123
6/6/2020, 6:40:58 PM [Nest] initing protect "Hallway": deviceId: 18B43000002F9CA0 structureId: 6dcb3130-e1d7-11e6-a6ca-22000b519123
6/6/2020, 6:40:58 PM [Nest] Initializing platform accessory "Hallway Thermostat"...
6/6/2020, 6:40:58 PM [Nest] Initializing platform accessory "Home Occupied"...
6/6/2020, 6:40:58 PM [Nest] Initializing platform accessory "Bedroom"...
6/6/2020, 6:40:58 PM [Nest] Initializing platform accessory "Hallway"...

**Comment by askovi** [comment] 2020-06-07 02:16
The issue is with your Nest Cam plugin. The nest-cam and nest-cam2 plugins have merged for a much better and more perform ant plugin. However it only works with Google Accounts. It no longer works with Nest Accounts. So you will have to migrate and redo your config for it.

**Comment by maswind** [comment] 2020-06-07 03:59
Aw nuts, I am not the biggest Google fan... and getting the Nest plug ins configured was a spot of a hassle...

Is there now a single plug in for both the thermostat and cam once I transfer the account to the Google API?

Thanks for the heads up. I will goof around with it tomorrow

**Comment by askovi** [comment] 2020-06-07 04:08
No, homebridge-nest is for everything but cameras and homebridge-nest-cam is for all cameras but you can use the exact same config for both. Same issueToken, same API Key, same Cookies.

**Closed** 2020-06-12 05:20 UTC
Labels: more info needed, plugins

**Comment by maswind** [comment] 2020-06-12 16:35
Thanks again for the assistance!

Tim
