### ISSUE TITLE
Version 3.3.6 or 4.0.31

### ISSUE THREAD

**Issue by Christian-CFP** [hoobs-org/HOOBS#1313] opened 2021-07-06 12:45 UTC
Is 4.0.31 official?
I get only 3.3.6 to update.

**Comment by Christian-CFP** [comment] 2021-07-06 12:47
I got this error after updating from 3.3.5 to 3.3.6:

6.7.2021, 14:46:07 AssertionError [ERR_ASSERTION]: Services must be created with a valid UUID.
    at new Service (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/Service.ts:289:11)
    at parseServiceJSON (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/AccessoryLoader.ts:124:19)
    at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/AccessoryLoader.ts:69:21
    at Array.forEach (<anonymous>)
    at Object.parseAccessoryJSON (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/AccessoryLoader.ts:68:17)
    at Server.createHAPAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:402:36)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:314:36
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:282:33)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:18)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
6.7.2021, 14:46:07 Got SIGTERM, shutting down Bridge...

**Comment by BobbySlope** [comment] 2021-07-06 12:56
Please wait with the update, till we officially announce it

**Comment by Christian-CFP** [comment] 2021-07-06 12:57
I updated it to 3.3.6 and I get the error message. Hoobs does not run anymore! Help needed.

**Comment by mkellsy** [comment] 2021-07-06 12:58
You are trying to upgrade to 3.3.6.
It looks like NPM might be giving you some issues. Try running this command.

```
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

**Comment by Christian-CFP** [comment] 2021-07-06 12:59
That's what I did.

**Comment by Christian-CFP** [comment] 2021-07-06 13:03
After that I get this error:

obsbs@hoobs:/home/hoobs/.hoobs/etc $ sudo npm install -g --unsafe-perm @hoobs/hoo
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/@hoobs/hoobs
npm ERR! dest /usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/@hoobs/hoobs' -> '/usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-06T13_00_37_296Z-debug.log
hoobs@hoobs:/home/hoobs/.hoobs/etc $ 

Than I did these commands:

hoobs@hoobs:/home/hoobs/.hoobs/etc $ sudo rm -fR ~/.npm

And:

hoobs@hoobs:/home/hoobs/.hoobs/etc $ sudo rm -fR /usr/local/lib/node_modules/@hoobs/hoobs

Than I ran the command again:

hoobs@hoobs:/home/hoobs/.hoobs/etc $ sudo npm install -g --unsafe-perm @hoobs/hoobs

**Comment by mkellsy** [comment] 2021-07-06 13:04
OK NPM root locked a file/ Run this
```
sudo rm -fR /usr/local/lib/node_modules/@hoobs/.hoobs-lk7qgySi
```
Then run
```
sudo npm install -g --unsafe-perm @hoobs/hoobs
```
again

**Comment by Christian-CFP** [comment] 2021-07-06 13:11
No, does not work. Still the same error. Stopped working.

**Comment by mkellsy** [comment] 2021-07-06 13:14
Try deleting the whole directory
```
sudo rm -fR /usr/local/lib/node_modules/@hoobs
```

Then run
```
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

**Comment by Christian-CFP** [comment] 2021-07-06 13:17
This ist what I also did before and now again. Nothing. Still the same error.

**Comment by davidvanvo** [comment] 2021-07-06 13:18
> Try deleting the whole directory
> 
> ```
> sudo rm -fR /usr/local/lib/node_modules/@hoobs
> ```
> 
> Then run
> 
> ```
> sudo npm install -g --unsafe-perm @hoobs/hoobs
> ```

I get the following error during installation

> bufferutil@4.0.3 install /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bufferutil
> node-gyp-build

> node-pty@0.9.0 install /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty
> node scripts/install.js

make: Entering directory '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
../src/unix/pty.cc: In function 'void pty_after_waitpid(uv_async_t*)':
../src/unix/pty.cc:486:43: warning: 'void* memset(void*, int, size_t)' writing to an object of type 'class Nan::Persistent<v8::Function>' with no trivial copy-assignment [-Wclass-memaccess]
   memset(&baton->cb, -1, sizeof(baton->cb));
                                           ^
In file included from ../../nan/nan.h:405,
                 from ../src/unix/pty.cc:20:
../../nan/nan_persistent_12_inl.h:12:40: note: 'class Nan::Persistent<v8::Function>' declared here
 template<typename T, typename M> class Persistent :
                                        ^~~~~~~~~~
In file included from ../../nan/nan.h:56,
                 from ../src/unix/pty.cc:20:
../src/unix/pty.cc: At global scope:
/root/.cache/node-gyp/12.14.1/include/node/node.h:560:43: warning: cast between incompatible function types from 'void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)' {aka 'void (*)(v8::Local<v8::Object>)'} to 'node::addon_register_func' {aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)'} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/root/.cache/node-gyp/12.14.1/include/node/node.h:594:3: note: in expansion of macro 'NODE_MODULE_X'
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/unix/pty.cc:708:1: note: in expansion of macro 'NODE_MODULE'
 NODE_MODULE(pty, init)
 ^~~~~~~~~~~
In file included from /root/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:56,
                 from ../src/unix/pty.cc:20:
/root/.cache/node-gyp/12.14.1/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]':
/root/.cache/node-gyp/12.14.1/include/node/node_object_wrap.h:84:78:   required from here
/root/.cache/node-gyp/12.14.1/include/node/v8.h:10004:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<node::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/12.14.1/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]':
../../nan/nan_object_wrap.h:65:61:   required from here
/root/.cache/node-gyp/12.14.1/include/node/v8.h:10004:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
  SOLINK_MODULE(target) Release/obj.target/pty.node
  COPY Release/pty.node
make: Leaving directory '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/build'

> utf-8-validate@5.0.5 install /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/utf-8-validate
> node-gyp-build

> node-pty@0.9.0 postinstall /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty
> node scripts/post-install.js

> @hoobs/hoobs@3.3.6 postinstall /usr/local/lib/node_modules/@hoobs/hoobs
> bin/hoobs upgrade

**Comment by mkellsy** [comment] 2021-07-06 13:20
That's not actually an error. Its build output.

**Comment by Christian-CFP** [comment] 2021-07-06 13:24
Hoobs is at 3.3.6 but I get this error during start. And the service will not start.

**Comment by Christian-CFP** [comment] 2021-07-06 13:49
4.0.71 does work. 
But how can I restart the service in hoobs? No menu item found.

**Comment by davidvanvo** [comment] 2021-07-06 13:53
@Christian-CFP did you manually install 4.0.31 or did it show up as available as an upgrade through HOOBS UI?

**Comment by mkellsy** [comment] 2021-07-06 13:54
There is no single service anymore.
Go to the Bridges screen and restart the bridge.
Bridges also auto restart on plugin install and configuration changes.

**Comment by mkellsy** [comment] 2021-07-06 13:56
@davidvanvo
4.0.31 will show up as an upgrade in 3.3.6.

**Comment by davidvanvo** [comment] 2021-07-06 14:00
> @davidvanvo
> 4.0.31 will show up as an upgrade in 3.3.6.

I'm on 3.3.6 with the same issues but not seeing 4.0.31 as an upgrade

**Comment by mkellsy** [comment] 2021-07-06 14:05
What device are you using?

**Comment by davidvanvo** [comment] 2021-07-06 14:09
> What device are you using?

Raspberry Pi 4

**Comment by mkellsy** [comment] 2021-07-06 14:11
It doesn't show when you go to Menu -> System?

**Comment by davidvanvo** [comment] 2021-07-06 14:13
![HOOBS](https://user-images.githubusercontent.com/6198316/124615001-71952000-de3a-11eb-8bf3-86e66571c8e0.png)
not sure why but it does not

**Comment by mkellsy** [comment] 2021-07-06 14:15
Are you running on port 80?

**Comment by davidvanvo** [comment] 2021-07-06 14:18
> Are you running on port 80?

yes

**Comment by mkellsy** [comment] 2021-07-06 14:21
Run this
```
sudo systemctl status nginx
```
What does it say?

**Comment by davidvanvo** [comment] 2021-07-06 14:23
```
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2021-07-06 07:34:56 MDT; 46min ago
     Docs: man:nginx(8)
 Main PID: 551 (nginx)
    Tasks: 5 (limit: 4915)
   Memory: 4.4M
   CGroup: /system.slice/nginx.service
           ├─551 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
           ├─552 nginx: worker process
           ├─553 nginx: worker process
           ├─554 nginx: worker process
           └─555 nginx: worker process

Jul 06 07:34:56 hoobs systemd[1]: Starting A high performance web server and a reverse proxy server...
Jul 06 07:34:56 hoobs systemd[1]: Started A high performance web server and a reverse proxy server.
```

**Comment by Christian-CFP** [comment] 2021-07-06 14:24
> @Christian-CFP did you manually install 4.0.31 or did it show up as available as an upgrade through HOOBS UI?

It showed up in hoobs. And it's 4.0.71

**Comment by mkellsy** [comment] 2021-07-06 14:24
Yep a migration to 4.0.31 would have been UGLY. Let me think about what to do next.

**Comment by Christian-CFP** [comment] 2021-07-06 14:25
Hi am guessing it's a "new" error but hoobs works. 

6.7.2021, 16:02:22HOOBS-ServerERROR(node:3731) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 state.change listeners added to [Device]. Use emitter.setMaxListeners() to increase limit
6.7.2021, 16:02:22HOOBS-ServerERROR(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by Andybishop** [comment] 2021-07-06 14:33
I am having the same problems on a Ubuntu 20.04.2 LTS VM, upgrades to 3.3.6, services will not start/run and showing no option to upgrade to 4.0.31, I have run sudo npm install -g --unsafe-perm @hoobs/hoobs several times.

**Comment by Andybishop** [comment] 2021-07-06 14:37
I get the following:-
06/07/2021, 15:34:21 (node:32339) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
06/07/2021, 15:34:21 at AxiosDigest.getWwwAuth (/home/hoobs/.hoobs/node_modules/axios-digest/index.ts:69:13)
06/07/2021, 15:34:21 at process._tickCallback (internal/process/next_tick.js:68:7)
06/07/2021, 15:34:21 (node:32339) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)

**Comment by mkellsy** [comment] 2021-07-06 14:37
Run
```
node -v
```

**Comment by Andybishop** [comment] 2021-07-06 14:40
> Run
> 
> ```
> node -v
> ```

node -v
v10.19.0

**Comment by mkellsy** [comment] 2021-07-06 14:43
You need to upgrade Node.
You need to follow the guides to install Node 14.17.x on Ubuntu 20.04.2 LTS.

**Comment by Andybishop** [comment] 2021-07-06 15:08
Now running node -v I get v14.17.2 - I now get different errors..

06/07/2021, 16:03:38 AssertionError [ERR_ASSERTION]: Services must be created with a valid UUID.
    at new Service (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/Service.ts:289:11)
    at parseServiceJSON (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/AccessoryLoader.ts:124:19)
    at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/AccessoryLoader.ts:69:21
    at Array.forEach (<anonymous>)
    at Object.parseAccessoryJSON (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/AccessoryLoader.ts:68:17)
    at Server.createHAPAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:402:36)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:314:36
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:282:33)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:18)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

06/07/2021, 16:03:39 (node:2061) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)

**Comment by mkellsy** [comment] 2021-07-06 15:41
Try resetting your connection Menu -> Help -> Reset Connection
This will require re-pairing with HomeKit.

I am also looking into this error.

**Comment by Andybishop** [comment] 2021-07-06 15:43
> Try resetting your connection Menu -> Help -> Reset Connection
> This will require re-pairing with HomeKit.
> 
> I am also looking into this error.

I have a Veeam backup of the VM so I am able to restore back to last night backups and get it back up and running for now.  Thank you.

**Comment by davidvanvo** [comment] 2021-07-06 16:43
> Try resetting your connection Menu -> Help -> Reset Connection
> This will require re-pairing with HomeKit.
> 
> I am also looking into this error.

prefer not to re-pair everything. should I wait for an alternate solution?

**Comment by mkellsy** [comment] 2021-07-06 16:45
@davidvanvo what plugins do you have installed. I think I found a bug in HB/HAP.
I need to test.

**Comment by davidvanvo** [comment] 2021-07-06 16:48
> @davidvanvo what plugins do you have installed. I think I found a bug in HB/HAP.
> I need to test.

- homebridge-dummy
- homebridge-nest
- homebridge-node-alarm-dot-com
- homebridge-prowl-notification
- homebridge-ring
- homebridge-schedule
- homebridge-weather-plus

**Comment by mkellsy** [comment] 2021-07-06 18:24
@davidvanvo

Don't upgrade if you are already on 4.0. This is for the assert error in 3.3.5 and 3.3.6

I think I got this. You can upgrade to 3.3.7
You have to upgrade from the command line
```
sudo npm install -g --unsafe-perm @hoobs/hoobs@latest
```

You should see the migration if you are running on port 80 and are on a Pi 3B, 3B+ or 4B.

**Comment by davidvanvo** [comment] 2021-07-06 18:30
@mkellsy i can confirm that i'm now on 3.3.7 and I no longer see any errors.

in regards to 4.0.31+. should i be seeing this update shortly? should i avoid it?

**Comment by mkellsy** [comment] 2021-07-06 18:41
If it's not showing in the system screen, it won't migrate nicely.
* Must be on ARMv7l (Raspberry Pi 3B, 3B+ and 4B)
* Must be running on port 80

If you are on a Raspberry Pi and you think you are running on port 80.
NGINX is probably proxying, you must disable this first.

**Comment by Christian-CFP** [comment] 2021-07-06 19:35
4-0-71 Works nicely until now.
But there ist an error and I do not know why:

6.7.2021, 20:47:06HOOBS-ServerERROR(node:23325) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 state.change listeners added to [Device]. Use emitter.setMaxListeners() to increase limit
6.7.2021, 20:47:06HOOBS-ServerERROR(Use `node --trace-warnings ...` to show where the warning was created)

@davidvanvo 4.0.x works fine. But keep in mind if you update (if there is a prompt in HOOBS to do so) all your devices disappear from HomeKit but reappear after afterwards. Thats ok but you will loose all your automations/sceens because of this.

**Comment by mkellsy** [comment] 2021-07-06 19:38
There's an update. There is a 4 hour cache on this.

To update sooner
Menu -> Hub Settings click on Clear Cache

Then close the Hub Settings

Then Check for Updates

**Comment by Christian-CFP** [comment] 2021-07-06 19:38
@mkellsy Do me a favour if I missed it. If there is a documentation please tell me.
The different Bridges. What are they for?
Is it something like Docker? Or only like a group?
Whats the intention behind separating different types of Bridges?

**Comment by mkellsy** [comment] 2021-07-06 19:40
You can separate your plugins.
Think of a Bridge as a complete Homebridge instance.

So if you have a problem plugin that crashes all the time, you can put it on it's own bridge and it won't take down the others.

It also allows you to add more then 99 or so items to HomeKit.

Plus it is more stable.

**Comment by Christian-CFP** [comment] 2021-07-06 19:43
> There's an update. There is a 4 hour cache on this.
> 
> To update sooner
> Menu -> Hub Settings click on Clear Cache
> 
> Then close the Hub Settings
> 
> Then Check for Updates

Ok. Thx. Updated to 4.0.72. Error still remains.

Is it maybe the Harmony Plugin that causes this? Because in the Log it appears just right after initializing (but the plugin works fine)
:
21:40:41HOOBS-ServerSamsungDidFinishLaunching
21:40:41HOOBS-ServerSamsung(Samsung)INFO - Loading activities...
21:40:41HOOBS-ServerERROR(node:27622) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 state.change listeners added to [Device]. Use emitter.setMaxListeners() to increase limit
21:40:41HOOBS-ServerERROR(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by mkellsy** [comment] 2021-07-06 19:45
It's just a warning. Doesn't actually hurt anything.

I will look into this.

**Comment by Christian-CFP** [comment] 2021-07-06 19:48
THX and good job on HOOBS 4!
Many more information e.g. when updating it shows me what its doing. And so on.

To all of you. A HUGE Thank You!

**Comment by Andybishop** [comment] 2021-07-06 20:08
I managed to get 3.3.7 installed with sudo npm install -g --unsafe-perm @hoobs/hoobs@latest, but no newer version showing as available.

**Comment by mkellsy** [comment] 2021-07-06 20:11
4.0 is only available for Raspberry Pi.
When we get this large userbase upgraded I can focus on other systems.

**Comment by Andybishop** [comment] 2021-07-06 20:19
> 4.0 is only available for Raspberry Pi.
> When we get this large userbase upgraded I can focus on other systems.

Ah right no problem, I will keep an eye for updates.  Thanks.

**Comment by ColinScattergood** [comment] 2021-07-07 05:17
> 4.0 is only available for Raspberry Pi.
> 
> When we get this large userbase upgraded I can focus on other systems.

I'm having the same issue and running on an Rpi3. Any ideas?

**Comment by Christian-CFP** [comment] 2021-07-07 10:35
How can I set debug log to on?

**Comment by bwp91** [comment] 2021-07-07 10:38
> How can I set debug log to on?

There is a small "bug" icon ↓ at the top of the log screen. I think it's that!

<img width="194" alt="Screenshot 2021-07-07 at 11 36 32" src="https://user-images.githubusercontent.com/43026681/124745339-a034f880-df17-11eb-8edc-bd33f547f4b5.png">

**Comment by Christian-CFP** [comment] 2021-07-07 10:39
No. I mean the homebridge debug mode.

**Comment by Christian-CFP** [comment] 2021-07-07 10:45
Stop service and run hoobs -d?
Is there a way inside hoobs 4? I mean a button like the bug one?

**Comment by oliverchapple** [comment] 2021-07-07 12:41
[2021-07-07T12_32_06_518Z-debug.log](https://github.com/hoobs-org/HOOBS/files/6777184/2021-07-07T12_32_06_518Z-debug.log)

got a log here trying to update to 4 v but this sudo npm install -g --unsafe-perm @hoobs/hoobs comes up with error

I did update to 3.3.7 thought.

thanks Oliver hope that helps

**Comment by mkellsy** [comment] 2021-07-07 14:38
@Christian-CFP
This issue is starting to collect other issues. Please open this in a new issue.
The debug mode is something we will have to change.

@oliverchapple
Please open a your own issue. Your problem is different then this issue.

I am closing this issue because the original issue has been addressed.

**Closed by mkellsy** 2021-07-07 14:38 UTC
