### ISSUE TITLE
Node Won't Update in 2.1.1

### ISSUE THREAD

**Issue by OfficialKaos** [hoobs-org/HOOBS#244] opened 2019-11-15 21:42 UTC
node won't update in v2.1.1

**Comment by mkellsy** [comment] 2019-11-16 03:08
How are you trying to upgrade node?

**Comment by OfficialKaos** [comment] 2019-11-16 06:53
hoobs-update

**Comment by mkellsy** [comment] 2019-11-16 14:17
I think it is caused by n not finding Node for ARM. I am looking into a different way to install Node LTS.

**Comment by mkellsy** [comment] 2019-11-16 20:49
N was not finding the ARM version properly. I changed the Node update script to install Node manually.

Fixed in 3.0.0-beta.73

**Closed by mkellsy** 2019-11-16 20:49 UTC
Labels: 2.1.1

**Comment by OfficialKaos** [comment] 2019-11-16 22:51
Excellent thank you, How do you do a manual install on 2.1.1?

**Comment by mkellsy** [comment] 2019-11-16 22:55
2.1.1 doesn't have a manual install process.

**Comment by OfficialKaos** [comment] 2019-11-16 22:57
will it be possible to update the node in 2.1.1?

**Comment by OfficialKaos** [comment] 2019-11-16 22:58
the cmd hoops-update in terminal doesn’t work anymore

**Comment by mkellsy** [comment] 2019-11-16 23:21
hoobs-update in 2.1.1 only updates Node.

HOOBS 3 is different code altogether. In 2.1.1 we run homebridge-config-ui-x, but Oznu, the developer, left the HOOBS org. Since Oznu owns all of that code, we don't have access to change or fix it anymore. hoobs-update doesn't always work and we can't fix it.

I joined HOOBS a few days later, and was already working on a project to replace homebridge-config-ui-x, I never liked how it works. homebridge-config-ui-x is a clone of a my homebridge-config-ui plugin that I retired about 4 years ago, because I wanted to make a software stack that made Homebridge easier and more stable. HOOBS 3 is a continuation of that work.

I donated the code to HOOBS, so we are now on our own code that we control. So some of the commands are different, but now we can fix things and faster too.

To update Node manually on a Raspberry Pi, you can run these commands.

First gain root access
```
sudo -i
```

Make sure curl and tar are on the system
```
apt-get install -y curl tar
```

Download the LTS version of Node
```
curl -O https://nodejs.org/dist/v12.13.0/node-v12.13.0-linux-armv7l.tar.gz
```

Install Node LTS
```
tar -xzf ./node-v12.13.0-linux-armv7l.tar.gz -C /usr/local --strip-components=1 --no-same-owner
```

Cleanup
```
rm -f ./node-v12.13.0-linux-armv7l.tar.gz
```

Exit root
```
exit
```

You can reboot to restart all of the services.

If you want to manually install HOOBS 3 we have that documented
https://github.com/hoobs-org/HOOBS/wiki/2.5.2-Debian-Installation

**Comment by OfficialKaos** [comment] 2019-11-16 23:26
OK great, Thank you , looking forward to the final release  of HOOBS 3 and thanks for all the great work and fast responses
