### ISSUE TITLE
Add ability to send Bug Report; Feature Request and Plugin Issue into GH from HOOBS

### ISSUE THREAD

**Issue by jqnatividad** [hoobs-org/HOOBS#455] opened 2020-01-29 17:22 UTC
**Is your feature request related to a problem? Please describe.**
As a HOOBS user, I want to be able to quickly send a Bug Report/Feature Request/Plugin Issue right from HOOBS UI itself, with HOOBS taking care of sending a properly anonymized manifest of all the required information (Configuration, Log, Plugin list, etc.).  Assembling an issue manually using the templates is tedious and inefficient as there is a lot of back-and-forth as evinced from the current issues in this repo.

**Describe the solution you'd like**
You can create a ticket right from HOOBS, which autopopulates GitHub issues.

**Describe alternatives you've considered**
For paying customers, perhaps, their ticket can be prioritized and/or entered into a proper support ticketing system (e.g. zendesk, etc), with option for remote access.

**Comment by mkellsy** [comment] 2020-01-29 19:48
Duplicate of #331

**Closed by mkellsy** 2020-01-29 19:48 UTC
Labels: discovery, enhancement
