### ISSUE TITLE
new Network and can not connect to hoobs.local

### ISSUE THREAD

**Issue by Hoobsnewbie** [hoobs-org/HOOBS#1439] opened 2021-08-02 22:23 UTC
description
Could not access hoobs.local after changing network equipment and network information. I am also not getting a wireless access point to connect via WIFI.

Version
Please include the version of HOOBS you are using. - i don't know the updated version. It is 3. something.

Did you upgrade
I have no upgraded since I am unable to get in.

{x} Yes
No

Previous version
If you upgrade, please let us know your previous version.

Did you originally upgrade to HOOBS 3 from HOOBS 2.1.1? - Yes a while ago
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.

{x} Yes
No
What device are you using?
Please let us know the device you are running HOOBS on. 

 [X ] HOOBS Box
 HOOBS SD Card
 Custom Install
If this is a custom install, what's your operating system?
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

List your plugins
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

- Alarm.com 
- Ring 

Post your config
This can be found in the interface, Configuration -> Advanced or you can get it via SSH cat ~/.hoobs/etc/config.json - I am unable to get in.

Remove any passwords from the config file. This is public.
POST CONFIG HERE
Post your log
You can get the log from the interface. This is in the Log section.

POST LOG HERE
Additional context

**Comment by mkellsy** [comment] 2021-08-03 03:14
You will need to reboot the device. (unplug and plug back in)

If you have your old WiFi router on, try turning it off then reboot the box. When it can't connect it will show the HOOBS access point to reconfigure.

If you are running 4.0 you can try using the desktop app
https://support.hoobs.org/downloads/desktop
(this will not work for 3.3)

The other thing you can try is to plugin in the network cable directly to your switch or router. Then reboot it.

**Comment by mkellsy** [comment] 2021-08-03 03:16
Duplicate of #1437

**Closed by mkellsy** 2021-08-03 03:16 UTC
