### ISSUE TITLE
Homebridge-platform-orvibo

### ISSUE THREAD

**Issue by khowell20454** [hoobs-org/HOOBS#317] opened 2019-12-12 05:25 UTC
I try to install the Homebridge-platform-orvibo plug-in, it looks like it is installing but nothing happens. Doesn’t show as an installed plug-in nor does it show in the configuration as a platform.

**Comment by mkellsy** [comment] 2019-12-16 15:22
Please post your logs.

**Comment by khowell20454** [comment] 2019-12-17 01:10
Here’s logs:
[12/16/2019, 19:02:14] HOOBS listning on port 8080.
[Homebridge] [12/16/2019, 19:02:15] Loaded config.json with 0 accessories and 2 platforms.
[Homebridge] [12/16/2019, 19:02:15] ---
[Homebridge] [12/16/2019, 19:02:16] Loaded plugin: homebridge-smartthings-tonesto7
[Homebridge] Homebridge Version: 2.4
[Homebridge] [12/16/2019, 19:02:16] Registering platform 'homebridge-smartthings.SmartThings'
[Homebridge] [12/16/2019, 19:02:16] ---
[Homebridge] [12/16/2019, 19:02:18] Loaded plugin: ring
[Homebridge] [12/16/2019, 19:02:18] Registering platform 'homebridge-ring.Ring'
[Homebridge] [12/16/2019, 19:02:18] ---
[Homebridge] [12/16/2019, 19:02:18] Loading 2 platforms...
[Homebridge] [12/16/2019, 19:02:18] [SmartThings] Initializing SmartThings platform...
[Homebridge] [12/16/2019, 19:02:18] [SmartThings] Fetching SmartThings devices.
[Homebridge] [12/16/2019, 19:02:18] [Ring] Initializing Ring platform...
[Homebridge] [12/16/2019, 19:02:18] Loading 0 accessories...
[Homebridge] [12/16/2019, 19:02:19] [SmartThings] Unknown Capabilities: []
[Homebridge] [12/16/2019, 19:02:19] [SmartThings] Initializing platform accessory 'Front Door Lock'...
[Homebridge] [12/16/2019, 19:02:19] [SmartThings] Initializing platform accessory 'Attic Flood Sensor'...
[Homebridge] [12/16/2019, 19:02:19] [SmartThings] Initializing platform accessory 'Laundry Flood Sensor'...
[Homebridge] [12/16/2019, 19:02:19] [SmartThings] Initializing platform accessory 'Living Room Lamp'...
[Homebridge] [12/16/2019, 19:02:19] [SmartThings] Initializing platform accessory 'Office Lamp'...
[Homebridge] X-HM://0023ISYWYHL45
[Homebridge] [12/16/2019, 19:02:19] [SmartThings] update_method: direct
[Homebridge] [12/16/2019, 19:02:19] Service is running on port 51826.
[Homebridge] [12/16/2019, 19:02:19] [SmartThings] Direct Connect Is Listening On 192.168.7.119:8000
[Homebridge] [12/16/2019, 19:02:19] [Ring] Configuring 1 cameras and 1 devices for location "Jenks" - locationId: 9y7ub1-3d8j7-0
[Homebridge] [12/16/2019, 19:02:19] [Ring] Adding new accessory doorbell_v3 Front Door
[Homebridge] [12/16/2019, 19:02:19] Front Door is running on port 34289.
[Homebridge] [12/16/2019, 19:02:19] Please add [Front Door] manually in Home app. Setup Code: 031-45-154
[Homebridge] [12/16/2019, 19:02:20] [SmartThings] SmartThings Hub Communication Established

**Comment by khowell20454** [comment] 2019-12-17 01:11
Doesn’t show orvibo in the configuration either.

**Comment by mkellsy** [comment] 2019-12-18 15:03
How are you installing the plugin. Are you installing via the terminal or the UI?

**Comment by mkellsy** [comment] 2019-12-18 18:13
Tested locally on Node 12.3

```
> sleep@3.0.1 install /Users/mkellsy/.hoobs/node_modules/sleep
> node-gyp rebuild
  CXX(target) Release/obj.target/node_sleep/sleep.o
../sleep.cc:6:11: error: no member named 'Handle' in namespace 'v8'
using v8::Handle;
      ~~~~^
../sleep.cc:42:30: error: too few arguments to function call, single argument 'context' was not specified
  sleep(info[0]->Uint32Value());
        ~~~~~~~~~~~~~~~~~~~~ ^
/Users/mkellsy/Library/Caches/node-gyp/12.13.1/include/node/v8.h:2611:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/mkellsy/Library/Caches/node-gyp/12.13.1/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../sleep.cc:54:31: error: too few arguments to function call, single argument 'context' was not specified
  usleep(info[0]->Uint32Value());
         ~~~~~~~~~~~~~~~~~~~~ ^
/Users/mkellsy/Library/Caches/node-gyp/12.13.1/include/node/v8.h:2611:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/mkellsy/Library/Caches/node-gyp/12.13.1/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../sleep.cc:62:52: error: too few arguments to function call, single argument 'context' was not specified
    Nan::New<FunctionTemplate>(Sleep)->GetFunction());
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/mkellsy/Library/Caches/node-gyp/12.13.1/include/node/v8.h:5995:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/mkellsy/Library/Caches/node-gyp/12.13.1/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../sleep.cc:64:53: error: too few arguments to function call, single argument 'context' was not specified
    Nan::New<FunctionTemplate>(USleep)->GetFunction());
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/mkellsy/Library/Caches/node-gyp/12.13.1/include/node/v8.h:5995:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/mkellsy/Library/Caches/node-gyp/12.13.1/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
5 errors generated.
make: *** [Release/obj.target/node_sleep/sleep.o] Error 1
gyp
 ERR!
 build error
gyp
 ERR! stack Error: `make` failed with exit code: 2
gyp ERR!
stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp
 ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mkellsy/.hoobs/node_modules/sleep
gyp
 ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm
ERR! code ELIFECYCLE
npm ERR! errno 1
npm

ERR! sleep@3.0.1 install: `node-gyp rebuild`
npm ERR!
 Exit status 1
npm ERR! 
npm ERR!
 Failed at the sleep@3.0.1 install script.
npm
ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm
 ERR! A complete log of this run can be found in:
npm ERR!     /Users/mkellsy/.npm/_logs/2019-12-18T18_11_48_490Z-debug.log
```

This plugin is not ready for the latest Node LTS version.

NEXT STEP
Create or add to the plugin's issues

**Comment by mkellsy** [comment] 2019-12-18 18:20
I created the issue on the plugins repo.
https://github.com/macnow/homebridge-platform-orvibo/issues/11

**Comment by mkellsy** [comment] 2019-12-18 20:17
I can confirm that this works on Node 10.17.0.

Fixed in 3.1.2

**Comment by BobbySlope** [comment] 2019-12-21 11:19
![A4AC9F14-AAFC-4A9A-BAA1-94A24BFAFF33](https://user-images.githubusercontent.com/50763727/71307265-15031900-23ec-11ea-868e-95b69cb12ba4.jpeg)

**Comment by mkellsy** [comment] 2019-12-21 16:28
This is because the plugin doesn't work in Node 12. This script will downgrade Node on your system.

```
wget -q -O - https://raw.githubusercontent.com/hoobs-org/HOOBS/master/install.sh | sudo bash -
```

**Closed** 2020-02-10 16:20 UTC
Labels: plugins, tracked
