### ISSUE TITLE
EHOSTUNREACH

### ISSUE THREAD

**Issue by chrstnkrmr** [hoobs-org/HOOBS#876] opened 2020-10-29 16:28 UTC
Hi, I have a problem:
A device (TV) does not appear in HOOBS anymore – without any system changes. The device always gets a static IP, it never changes and is still connected with the local network.
I got the following error:

[BraviaPlatform] Error:  Error: connect EHOSTUNREACH 192.168.188.8:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.188.8',
  port: 80
}

I expect the TV is reachable for HOOBS.

Any idea?
Thanks for an hint.

**Comment by chrstnkrmr** [comment] 2020-10-29 16:31
There is an unanswered issue in this backlog: https://github.com/hoobs-org/HOOBS/issues/841

**Comment by askovi** [comment] 2020-10-30 03:31
Duplicate of #841

**Closed by askovi** 2020-10-30 03:31 UTC
