### ISSUE TITLE
ScreenLogic platform not registering after plugin loaded

### ISSUE THREAD

**Issue by maxmuller** [hoobs-org/HOOBS#699] opened 2020-06-24 19:03 UTC
**Description**
ScreenLogic plugin is not showing as being published. I have other platforms working in HOOBS. This is the message from the log:

6/24/2020, 9:23:19 AM Loaded plugin "homebridge-screenlogic".
6/24/2020, 9:23:19 AM The requested platform "ScreenLogic" was not registered by any plugin.
6/24/2020, 9:23:19 AM Your config.json is requesting the platform "ScreenLogic" which has not been published by any installed plugins.

**Expected behavoir**
ScreenLogic loads

**Plugin name**
homebridge-screenlogic

**Please report the issue to the plugin developer**
I filed an issue in the support form and the developer doesn't use HOOBS so he directed me here.

**Version**
3.2.6

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ ] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [ X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X ] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install
**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY09O7",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "21:F4:A1:F8:DB:34"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "Camera-ffmpeg",
            "plugin_map": {
                "plugin_name": "homebridge-camera-ffmpeg"
            },
            "cameras": [
                {
                    "name": "Back Garage",
                    "videoConfig": {
                        "source": "-re -i rtsp://admin:******@192.168.2.230/Streaming/Channels/1",
                        "stillImageSource": "http://admin:******@192.168.2.230/tmpfs/auto.jpg",
                        "maxStreams": 2,
                        "maxWidth": 1920,
                        "maxHeight": 1280,
                        "maxFPS": 15
                    }
                },
                {
                    "name": "Garden",
                    "videoConfig": {
                        "source": "-re -i rtsp://admin:******@192.168.2.231/Streaming/Channels/1",
                        "stillImageSource": "http://admin:******@192.168.2.231/tmpfs/auto.jpg",
                        "maxStreams": 2,
                        "maxWidth": 1920,
                        "maxHeight": 1280,
                        "maxFPS": 15
                    }
                },
                {
                    "name": "Motor Court",
                    "videoConfig": {
                        "source": "-re -i rtsp://user:******@192.168.1.28/axis-media/media.amp?camera=1",
                        "stillImageSource": "http://user:******@192.168.1.28/jpg/1/image.jpg",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 480,
                        "maxFPS": 5
                    }
                },
                {
                    "name": "Back Lawn",
                    "videoConfig": {
                        "source": "-re -i rtsp://user:******@192.168.1.28/axis-media/media.amp?camera=3",
                        "stillImageSource": "http://user:******@192.168.1.28/jpg/3/image.jpg",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 480,
                        "maxFPS": 5
                    }
                },
                {
                    "name": "Garage",
                    "videoConfig": {
                        "source": "-re -i rtsp://user:******@192.168.1.28/axis-media/media.amp?camera=4",
                        "stillImageSource": "http://user:******@192.168.1.28/jpg/4/image.jpg",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 480,
                        "maxFPS": 5
                    }
                },
                {
                    "name": "Back Terrace",
                    "videoConfig": {
                        "source": "-re -i rtsp://user:******@192.168.1.28/axis-media/media.amp?camera=5",
                        "stillImageSource": "http://user:******@192.168.1.28/jpg/5/image.jpg",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 480,
                        "maxFPS": 5
                    }
                }
            ]
        },
        {
            "platform": "ScreenLogic",
            "plugin_map": {
                "plugin_name": "homebridge-screenlogic"
            },
            "hidePoolTemperatureSensor": false,
            "hideSpaTemperatureSensor": false,
            "hideAirTemperatureSensor": false,
            "hidePoolThermostat": false,
            "hideSpaThermostat": false,
            "statusPollingSeconds": 60
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
6/24/2020, 9:23:19 AM Loaded plugin "homebridge-camera-ffmpeg".
6/24/2020, 9:23:19 AM Loaded plugin "homebridge-screenlogic".
6/24/2020, 9:23:19 AM The requested platform "ScreenLogic" was not registered by any plugin.
6/24/2020, 9:23:19 AM Your config.json is requesting the platform "ScreenLogic" which has not been published by any installed plugins.
6/24/2020, 9:23:19 AM [Camera-ffmpeg] Configuring accessory Back Garage
6/24/2020, 9:23:19 AM [Camera-ffmpeg] Configuring accessory Motor Court
6/24/2020, 9:23:19 AM [Camera-ffmpeg] Configuring accessory Back Lawn
6/24/2020, 9:23:19 AM [Camera-ffmpeg] Configuring accessory Garden
6/24/2020, 9:23:19 AM [Camera-ffmpeg] Configuring accessory Garage
6/24/2020, 9:23:19 AM [Camera-ffmpeg] Configuring accessory Back Terrace
6/24/2020, 9:23:19 AM Bridge is running on port 51826.
```

**Additional context**

**Comment by DragonMyAss** [comment] 2020-06-24 20:42
I have the same issue, and it seems that the issue is that HOOBS doesn’t currently support Homebridge version 1.1.1, which is a requirement for the latest version of the ScreenLogic plugin.

**Comment by askovi** [comment] 2020-06-24 20:55
I'll submit a PR request with the fix for this to the plugin developer

**Comment by BobbySlope** [comment] 2020-06-24 23:05
solved via updating the plugin by plugin dev

**Closed by BobbySlope** 2020-06-24 23:05 UTC
Labels: discovery, plugins
