### ISSUE TITLE
Plugins completely missing after moving to Hoobs 3

### ISSUE THREAD

**Issue by Elch08** [hoobs-org/HOOBS#238] opened 2019-11-10 16:23 UTC

**Comment by Elch08** [comment] 2019-11-10 16:27
I moved over to Hoobs 3 which I deeply regretted afterwards. 
Only my smappee plugin, Lifx plugin and dyson plugin were transferred. The hue plugin, the roomba plugin, the wemo plugin and the harmony hub plugin were not transferred. 
Worse was, that I could not install the missing plugins and also not uninstall the existing ones. After editing the config.json I could suddenly install wemo, but smappe and lifx were gone. From this moment on, all was frozen. I could not uninstall wemo and so the only remedy was going back to hoobs 2.
Hoobs 3 is a beta so I must wait until it runs stable.

**Comment by mkellsy** [comment] 2019-11-11 20:03
Duplicate of #235

**Closed by mkellsy** 2019-11-11 20:03 UTC
