### ISSUE TITLE
Set Static IP address for HOOBS

### ISSUE THREAD

**Issue by fwiehl** [hoobs-org/HOOBS#498] opened 2020-02-28 06:41 UTC
Is it possible to set the DHCP of HOOBS to a static IP? I haven't found a function on the Hoobs Surface, perhaps somebody tell me to change tie IP manual over the SSH or the terminal.
Thank you so much.

**Comment by askovi** [comment] 2020-02-28 06:42
You can do that from your router's admin page in the DHCP table. Assign a static IP to the MAC address of the HOOBS Box.

**Comment by fwiehl** [comment] 2020-02-28 06:50
This is unfortunately not possible, because my Fritz!box 7590 is configuered as static environment. In this configuration I'm not able to set the static mac address.

**Comment by mkellsy** [comment] 2020-02-28 16:05
Duplicate of #143

**Closed by mkellsy** 2020-02-28 16:05 UTC
Labels: discovery, enhancement
