### ISSUE TITLE
HOOBS & HUE

### ISSUE THREAD

**Issue by Christian-CFP** [hoobs-org/HOOBS#1146] opened 2021-03-14 15:19 UTC
Since 0.13.0 of HUE Plugin the whole Hoobs crashes!
Cant even go back to 0.12.26. Still crashes!

Need help!

**Comment by Christian-CFP** [comment] 2021-03-14 15:25
Hue release info. Needed HB 1.3.3

**Comment by Christian-CFP** [comment] 2021-03-14 16:14
It seems only if I add the IPs (hosts) of the bridges. If added, it stops working even if I delete the IPs...

**Comment by mkellsy** [comment] 2021-03-14 17:14
Duplicate of #1147

Update to version 3.3.4.

**Closed by mkellsy** 2021-03-14 17:14 UTC
Labels: bug, discovery
